import { db } from "./db";
import { trails, campgrounds, marketplaceListings, users } from "@shared/schema";
import bcrypt from "bcrypt";

async function seed() {
  console.log("Seeding database...");

  const existingTrails = await db.select().from(trails);
  if (existingTrails.length > 0) {
    console.log("Database already seeded, skipping.");
    return;
  }

  const passwordHash = await bcrypt.hash("Demo@1234", 12);
  const [demoUser] = await db.insert(users).values({
    firstName: "Trail",
    lastName: "Explorer",
    email: "demo@verdara.com",
    passwordHash,
    emailVerified: true,
    tier: "Pro Adventurer",
    trailsCompleted: 47,
    speciesIdentified: 156,
    conservationDonated: 250,
    equipmentTracked: 23,
  }).returning();

  await db.insert(trails).values([
    {
      name: "Cascade Ridge Loop",
      location: "Mt. Rainier National Park, WA",
      distance: "8.4 mi",
      elevation: "2,100 ft",
      difficulty: "Moderate",
      rating: 4.8,
      reviews: 342,
      image: "/images/cat-hiking.jpg",
      description: "A stunning loop trail featuring wildflower meadows, old-growth forest, and panoramic mountain views.",
      activityType: "hiking",
      features: ["Wildflowers", "Mountain Views", "Wildlife"],
      isFeatured: true,
      lat: 46.8523,
      lng: -121.7603,
    },
    {
      name: "Eagle Creek Trail",
      location: "Columbia River Gorge, OR",
      distance: "12.0 mi",
      elevation: "1,400 ft",
      difficulty: "Hard",
      rating: 4.9,
      reviews: 891,
      image: "/images/cat-camping.jpg",
      description: "Famous for Tunnel Falls and Punchbowl Falls. One of the most scenic hikes in the Pacific Northwest.",
      activityType: "hiking",
      features: ["Waterfalls", "River", "Old Growth"],
      isFeatured: true,
      lat: 45.6387,
      lng: -121.9197,
    },
    {
      name: "Rattlesnake Ledge",
      location: "North Bend, WA",
      distance: "4.0 mi",
      elevation: "1,160 ft",
      difficulty: "Easy",
      rating: 4.5,
      reviews: 1204,
      image: "/images/cat-rock-climbing.jpg",
      description: "Popular family-friendly hike with rewarding lake views from the ledge summit.",
      activityType: "hiking",
      features: ["Lake Views", "Family Friendly", "Dog Friendly"],
      isFeatured: true,
      lat: 47.4353,
      lng: -121.7714,
    },
    {
      name: "Enchantment Lakes",
      location: "Leavenworth, WA",
      distance: "18.0 mi",
      elevation: "4,400 ft",
      difficulty: "Expert",
      rating: 4.95,
      reviews: 567,
      image: "/images/cat-fishing.jpg",
      description: "Alpine wonderland with pristine lakes, golden larches, and mountain goats. Permit required.",
      activityType: "hiking",
      features: ["Alpine Lakes", "Permit Required", "Larch Trees"],
      isFeatured: true,
      lat: 47.5280,
      lng: -120.8220,
    },
    {
      name: "Tiger Mountain Trail",
      location: "Issaquah, WA",
      distance: "5.6 mi",
      elevation: "1,800 ft",
      difficulty: "Moderate",
      rating: 4.3,
      reviews: 456,
      image: "/images/cat-mountain-biking.jpg",
      description: "Well-maintained trail system popular with hikers and mountain bikers alike.",
      activityType: "mountain biking",
      features: ["Forest", "Multi-Use", "Year Round"],
      isFeatured: false,
      lat: 47.4743,
      lng: -122.0860,
    },
    {
      name: "Olympic Discovery Trail",
      location: "Olympic Peninsula, WA",
      distance: "15.2 mi",
      elevation: "800 ft",
      difficulty: "Easy",
      rating: 4.6,
      reviews: 289,
      image: "/images/cat-electric-mobility.jpg",
      description: "Paved multi-use path perfect for cycling, running, and electric mobility devices.",
      activityType: "cycling",
      features: ["Paved", "Coastal Views", "Accessible"],
      isFeatured: false,
      lat: 48.0765,
      lng: -123.4307,
    },
    {
      name: "Deception Pass State Park",
      location: "Whidbey Island, WA",
      distance: "3.8 mi",
      elevation: "600 ft",
      difficulty: "Easy",
      rating: 4.7,
      reviews: 723,
      image: "/images/cat-water-sports.jpg",
      description: "Iconic bridge views, tidepools, and old-growth forests on the rugged coastline.",
      activityType: "hiking",
      features: ["Bridge Views", "Tidepools", "Beach"],
      isFeatured: false,
      lat: 48.3935,
      lng: -122.6456,
    },
    {
      name: "Crystal Mountain Backcountry",
      location: "Crystal Mountain, WA",
      distance: "6.2 mi",
      elevation: "3,200 ft",
      difficulty: "Hard",
      rating: 4.4,
      reviews: 198,
      image: "/images/cat-winter-sports.jpg",
      description: "Challenging backcountry terrain with powder skiing and snowshoeing in winter months.",
      activityType: "winter sports",
      features: ["Backcountry", "Powder", "Avalanche Awareness"],
      isFeatured: false,
      lat: 46.9348,
      lng: -121.4742,
    },
  ]);

  await db.insert(campgrounds).values([
    {
      name: "Ohanapecosh Campground",
      location: "Mt. Rainier National Park, WA",
      price: 25,
      rating: 4.6,
      sites: 188,
      amenities: ["Flush Toilets", "Water", "Fire Rings", "Ranger Programs"],
      image: "/images/cat-camping.jpg",
      description: "Old-growth forest campground near hot springs and waterfalls.",
    },
    {
      name: "Sol Duc Hot Springs",
      location: "Olympic National Park, WA",
      price: 35,
      rating: 4.8,
      sites: 82,
      amenities: ["Hot Springs", "Flush Toilets", "Showers", "Store"],
      image: "/images/cat-hiking.jpg",
      description: "Resort campground with natural mineral hot springs and rainforest trails.",
    },
    {
      name: "Deception Pass State Park",
      location: "Whidbey Island, WA",
      price: 30,
      rating: 4.5,
      sites: 167,
      amenities: ["Flush Toilets", "Showers", "Beach Access", "Boat Launch"],
      image: "/images/cat-water-sports.jpg",
      description: "Coastal camping with stunning bridge views and tide pool exploration.",
    },
    {
      name: "Leavenworth KOA",
      location: "Leavenworth, WA",
      price: 45,
      rating: 4.3,
      sites: 120,
      amenities: ["Pool", "WiFi", "Store", "Playground", "Hot Tub"],
      image: "/images/cat-rock-climbing.jpg",
      description: "Full-service campground near Bavarian village and alpine trails.",
    },
  ]);

  await db.insert(marketplaceListings).values([
    {
      sellerId: demoUser.id,
      species: "Black Walnut",
      grade: "FAS Select",
      dimensions: "8/4 x 8\" x 10'",
      pricePerBf: 12.50,
      sellerName: "Pacific NW Timber",
      trustLevel: 4,
      trustScore: 945,
      location: "Portland, OR",
      image: "/images/cat-hunting.jpg",
      description: "Premium air-dried black walnut lumber. Stunning grain patterns, kiln-ready.",
    },
    {
      sellerId: demoUser.id,
      species: "Western Red Cedar",
      grade: "Clear Heart",
      dimensions: "4/4 x 6\" x 8'",
      pricePerBf: 8.75,
      sellerName: "Cascade Wood Supply",
      trustLevel: 3,
      trustScore: 872,
      location: "Seattle, WA",
      image: "/images/cat-camping.jpg",
      description: "Old-growth salvage cedar. Perfect for outdoor furniture and siding.",
    },
    {
      sellerId: demoUser.id,
      species: "Douglas Fir",
      grade: "#1 Common",
      dimensions: "6/4 x 10\" x 12'",
      pricePerBf: 5.25,
      sellerName: "Olympic Lumber Co",
      trustLevel: 2,
      trustScore: 720,
      location: "Olympia, WA",
      image: "/images/cat-fishing.jpg",
      description: "Structural-grade Douglas Fir timbers. Sustainably harvested.",
    },
    {
      sellerId: demoUser.id,
      species: "Bigleaf Maple",
      grade: "Figured/Quilted",
      dimensions: "8/4 x 12\" x 6'",
      pricePerBf: 18.00,
      sellerName: "Artisan Hardwoods NW",
      trustLevel: 4,
      trustScore: 960,
      location: "Eugene, OR",
      image: "/images/cat-mountain-biking.jpg",
      description: "Rare quilted maple with exceptional figure. Instrument and fine furniture grade.",
    },
    {
      sellerId: demoUser.id,
      species: "Oregon White Oak",
      grade: "FAS",
      dimensions: "4/4 x 8\" x 8'",
      pricePerBf: 9.50,
      sellerName: "Valley Oak Woodworks",
      trustLevel: 3,
      trustScore: 835,
      location: "Salem, OR",
      image: "/images/cat-electric-mobility.jpg",
      description: "Local white oak with beautiful grain. Wine barrel and cabinet grade.",
    },
  ]);

  console.log("Seeding complete!");
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Seed error:", err);
    process.exit(1);
  });
