import { db } from "./db";
import { trails, campgrounds, marketplaceListings, users, activityLocations } from "@shared/schema";
import bcrypt from "bcrypt";

async function seed() {
  console.log("Seeding database...");

  const existingTrails = await db.select().from(trails);
  if (existingTrails.length > 0) {
    console.log("Database already seeded, skipping.");
    return;
  }

  const passwordHash = await bcrypt.hash("Demo@1234", 12);
  const [demoUser] = await db.insert(users).values({
    firstName: "Trail",
    lastName: "Explorer",
    email: "demo@verdara.com",
    passwordHash,
    emailVerified: true,
    tier: "Pro Adventurer",
    trailsCompleted: 47,
    speciesIdentified: 156,
    conservationDonated: 250,
    equipmentTracked: 23,
  }).returning();

  await db.insert(trails).values([
    {
      name: "Cascade Ridge Loop",
      location: "Mt. Rainier National Park, WA",
      distance: "8.4 mi",
      elevation: "2,100 ft",
      difficulty: "Moderate",
      rating: 4.8,
      reviews: 342,
      image: "/images/cat-hiking.jpg",
      description: "A stunning loop trail featuring wildflower meadows, old-growth forest, and panoramic mountain views.",
      activityType: "hiking",
      features: ["Wildflowers", "Mountain Views", "Wildlife"],
      isFeatured: true,
      lat: 46.8523,
      lng: -121.7603,
    },
    {
      name: "Eagle Creek Trail",
      location: "Columbia River Gorge, OR",
      distance: "12.0 mi",
      elevation: "1,400 ft",
      difficulty: "Hard",
      rating: 4.9,
      reviews: 891,
      image: "/images/cat-camping.jpg",
      description: "Famous for Tunnel Falls and Punchbowl Falls. One of the most scenic hikes in the Pacific Northwest.",
      activityType: "hiking",
      features: ["Waterfalls", "River", "Old Growth"],
      isFeatured: true,
      lat: 45.6387,
      lng: -121.9197,
    },
    {
      name: "Rattlesnake Ledge",
      location: "North Bend, WA",
      distance: "4.0 mi",
      elevation: "1,160 ft",
      difficulty: "Easy",
      rating: 4.5,
      reviews: 1204,
      image: "/images/cat-rock-climbing.jpg",
      description: "Popular family-friendly hike with rewarding lake views from the ledge summit.",
      activityType: "hiking",
      features: ["Lake Views", "Family Friendly", "Dog Friendly"],
      isFeatured: true,
      lat: 47.4353,
      lng: -121.7714,
    },
    {
      name: "Enchantment Lakes",
      location: "Leavenworth, WA",
      distance: "18.0 mi",
      elevation: "4,400 ft",
      difficulty: "Expert",
      rating: 4.95,
      reviews: 567,
      image: "/images/cat-fishing.jpg",
      description: "Alpine wonderland with pristine lakes, golden larches, and mountain goats. Permit required.",
      activityType: "hiking",
      features: ["Alpine Lakes", "Permit Required", "Larch Trees"],
      isFeatured: true,
      lat: 47.5280,
      lng: -120.8220,
    },
    {
      name: "Tiger Mountain Trail",
      location: "Issaquah, WA",
      distance: "5.6 mi",
      elevation: "1,800 ft",
      difficulty: "Moderate",
      rating: 4.3,
      reviews: 456,
      image: "/images/cat-mountain-biking.jpg",
      description: "Well-maintained trail system popular with hikers and mountain bikers alike.",
      activityType: "mountain biking",
      features: ["Forest", "Multi-Use", "Year Round"],
      isFeatured: false,
      lat: 47.4743,
      lng: -122.0860,
    },
    {
      name: "Olympic Discovery Trail",
      location: "Olympic Peninsula, WA",
      distance: "15.2 mi",
      elevation: "800 ft",
      difficulty: "Easy",
      rating: 4.6,
      reviews: 289,
      image: "/images/cat-electric-mobility.jpg",
      description: "Paved multi-use path perfect for cycling, running, and electric mobility devices.",
      activityType: "cycling",
      features: ["Paved", "Coastal Views", "Accessible"],
      isFeatured: false,
      lat: 48.0765,
      lng: -123.4307,
    },
    {
      name: "Deception Pass State Park",
      location: "Whidbey Island, WA",
      distance: "3.8 mi",
      elevation: "600 ft",
      difficulty: "Easy",
      rating: 4.7,
      reviews: 723,
      image: "/images/cat-water-sports.jpg",
      description: "Iconic bridge views, tidepools, and old-growth forests on the rugged coastline.",
      activityType: "hiking",
      features: ["Bridge Views", "Tidepools", "Beach"],
      isFeatured: false,
      lat: 48.3935,
      lng: -122.6456,
    },
    {
      name: "Crystal Mountain Backcountry",
      location: "Crystal Mountain, WA",
      distance: "6.2 mi",
      elevation: "3,200 ft",
      difficulty: "Hard",
      rating: 4.4,
      reviews: 198,
      image: "/images/cat-winter-sports.jpg",
      description: "Challenging backcountry terrain with powder skiing and snowshoeing in winter months.",
      activityType: "winter sports",
      features: ["Backcountry", "Powder", "Avalanche Awareness"],
      isFeatured: false,
      lat: 46.9348,
      lng: -121.4742,
    },
  ]);

  await db.insert(campgrounds).values([
    {
      name: "Ohanapecosh Campground",
      location: "Mt. Rainier National Park, WA",
      price: 25,
      rating: 4.6,
      sites: 188,
      amenities: ["Flush Toilets", "Water", "Fire Rings", "Ranger Programs"],
      image: "/images/cat-camping.jpg",
      description: "Old-growth forest campground near hot springs and waterfalls.",
    },
    {
      name: "Sol Duc Hot Springs",
      location: "Olympic National Park, WA",
      price: 35,
      rating: 4.8,
      sites: 82,
      amenities: ["Hot Springs", "Flush Toilets", "Showers", "Store"],
      image: "/images/cat-hiking.jpg",
      description: "Resort campground with natural mineral hot springs and rainforest trails.",
    },
    {
      name: "Deception Pass State Park",
      location: "Whidbey Island, WA",
      price: 30,
      rating: 4.5,
      sites: 167,
      amenities: ["Flush Toilets", "Showers", "Beach Access", "Boat Launch"],
      image: "/images/cat-water-sports.jpg",
      description: "Coastal camping with stunning bridge views and tide pool exploration.",
    },
    {
      name: "Leavenworth KOA",
      location: "Leavenworth, WA",
      price: 45,
      rating: 4.3,
      sites: 120,
      amenities: ["Pool", "WiFi", "Store", "Playground", "Hot Tub"],
      image: "/images/cat-rock-climbing.jpg",
      description: "Full-service campground near Bavarian village and alpine trails.",
    },
  ]);

  await db.insert(marketplaceListings).values([
    {
      sellerId: demoUser.id,
      species: "Black Walnut",
      grade: "FAS Select",
      dimensions: "8/4 x 8\" x 10'",
      pricePerBf: 12.50,
      sellerName: "Pacific NW Timber",
      trustLevel: 4,
      trustScore: 945,
      location: "Portland, OR",
      image: "/images/cat-hunting.jpg",
      description: "Premium air-dried black walnut lumber. Stunning grain patterns, kiln-ready.",
    },
    {
      sellerId: demoUser.id,
      species: "Western Red Cedar",
      grade: "Clear Heart",
      dimensions: "4/4 x 6\" x 8'",
      pricePerBf: 8.75,
      sellerName: "Cascade Wood Supply",
      trustLevel: 3,
      trustScore: 872,
      location: "Seattle, WA",
      image: "/images/cat-camping.jpg",
      description: "Old-growth salvage cedar. Perfect for outdoor furniture and siding.",
    },
    {
      sellerId: demoUser.id,
      species: "Douglas Fir",
      grade: "#1 Common",
      dimensions: "6/4 x 10\" x 12'",
      pricePerBf: 5.25,
      sellerName: "Olympic Lumber Co",
      trustLevel: 2,
      trustScore: 720,
      location: "Olympia, WA",
      image: "/images/cat-fishing.jpg",
      description: "Structural-grade Douglas Fir timbers. Sustainably harvested.",
    },
    {
      sellerId: demoUser.id,
      species: "Bigleaf Maple",
      grade: "Figured/Quilted",
      dimensions: "8/4 x 12\" x 6'",
      pricePerBf: 18.00,
      sellerName: "Artisan Hardwoods NW",
      trustLevel: 4,
      trustScore: 960,
      location: "Eugene, OR",
      image: "/images/cat-mountain-biking.jpg",
      description: "Rare quilted maple with exceptional figure. Instrument and fine furniture grade.",
    },
    {
      sellerId: demoUser.id,
      species: "Oregon White Oak",
      grade: "FAS",
      dimensions: "4/4 x 8\" x 8'",
      pricePerBf: 9.50,
      sellerName: "Valley Oak Woodworks",
      trustLevel: 3,
      trustScore: 835,
      location: "Salem, OR",
      image: "/images/cat-electric-mobility.jpg",
      description: "Local white oak with beautiful grain. Wine barrel and cabinet grade.",
    },
  ]);

  console.log("Seeding complete!");
}

async function seedActivityLocations() {
  console.log("Checking activity_locations...");

  const existingLocations = await db.select().from(activityLocations);
  if (existingLocations.length > 0) {
    console.log("Activity locations already seeded, skipping.");
    return;
  }

  console.log("Seeding activity locations...");

  await db.insert(activityLocations).values([
    {
      type: "fishing",
      name: "Lake Fork Reservoir",
      location: "Lake Fork, TX",
      state: "Texas",
      description: "Premier trophy bass lake known for producing record largemouth bass. Over 27,000 acres of prime fishing waters with abundant structure and cover.",
      image: "/images/cat-fishing.jpg",
      rating: 4.9,
      reviews: 1842,
      difficulty: "Moderate",
      season: "Year-round, best March-June",
      regulations: "Slot limit 16-24 inches on largemouth bass. Daily bag limit 5. Valid TX fishing license required.",
      species: ["Largemouth Bass", "Crappie", "Channel Catfish", "Blue Catfish"],
      amenities: ["Boat Ramps", "Bait Shops", "Guide Services", "Campgrounds", "Fish Cleaning Stations"],
      tags: ["trophy bass", "reservoir", "boat fishing", "family friendly"],
      coordinates: { lat: 32.8818, lng: -95.5938 },
      metadata: { boat_access: "true", water_type: "freshwater", best_technique: "flipping and pitching" },
      isFeatured: true,
    },
    {
      type: "fishing",
      name: "Kenai River",
      location: "Cooper Landing, AK",
      state: "Alaska",
      description: "World-famous salmon river offering incredible runs of king, sockeye, and silver salmon. Crystal-clear turquoise waters flowing through stunning wilderness.",
      image: "/images/cat-water-sports.jpg",
      rating: 4.95,
      reviews: 2103,
      difficulty: "Moderate",
      season: "May-September",
      regulations: "Single-hook artificial lures only in certain sections. King salmon permits required. Check current ADF&G emergency orders.",
      species: ["King Salmon", "Sockeye Salmon", "Silver Salmon", "Rainbow Trout", "Dolly Varden"],
      amenities: ["Guide Services", "Drift Boat Access", "Campgrounds", "Lodges", "Fish Processing"],
      tags: ["salmon run", "fly fishing", "drift boat", "wilderness"],
      coordinates: { lat: 60.4900, lng: -149.8300 },
      metadata: { boat_access: "true", water_type: "freshwater river", best_technique: "drift fishing" },
      isFeatured: true,
    },
    {
      type: "fishing",
      name: "Chesapeake Bay",
      location: "Annapolis, MD",
      state: "Maryland",
      description: "The largest estuary in the US offering world-class striped bass fishing. Miles of shoreline, islands, and deep channels provide diverse angling opportunities.",
      image: "/images/cat-fishing.jpg",
      rating: 4.7,
      reviews: 1456,
      difficulty: "Easy",
      season: "April-November",
      regulations: "Striped bass minimum 19 inches. Seasonal closures apply. MD saltwater license required.",
      species: ["Striped Bass", "Blue Crab", "Bluefish", "Flounder", "White Perch"],
      amenities: ["Marinas", "Charter Boats", "Bait & Tackle Shops", "Restaurants", "Public Piers"],
      tags: ["saltwater", "charter fishing", "striped bass", "coastal"],
      coordinates: { lat: 38.9784, lng: -76.4922 },
      metadata: { boat_access: "true", water_type: "saltwater estuary", best_technique: "trolling" },
      isFeatured: false,
    },
    {
      type: "fishing",
      name: "Madison River",
      location: "Ennis, MT",
      state: "Montana",
      description: "Blue-ribbon trout stream flowing through pristine Montana valleys. Legendary dry fly fishing with prolific hatches and wild trout populations.",
      image: "/images/cat-camping.jpg",
      rating: 4.85,
      reviews: 987,
      difficulty: "Moderate",
      season: "June-October",
      regulations: "Catch and release in certain sections. Artificial lures only. MT fishing license required.",
      species: ["Brown Trout", "Rainbow Trout", "Mountain Whitefish"],
      amenities: ["Fly Shops", "Guide Services", "Wade Access Points", "Campgrounds"],
      tags: ["fly fishing", "trout stream", "wade fishing", "dry fly"],
      coordinates: { lat: 45.3469, lng: -111.7299 },
      metadata: { boat_access: "true", water_type: "freshwater river", best_technique: "dry fly" },
      isFeatured: true,
    },
    {
      type: "fishing",
      name: "Lake Okeechobee",
      location: "Clewiston, FL",
      state: "Florida",
      description: "Florida's inland sea spanning over 730 square miles. Exceptional bass fishing in vast grass flats, lily pads, and open water.",
      image: "/images/cat-water-sports.jpg",
      rating: 4.6,
      reviews: 1234,
      difficulty: "Easy",
      season: "Year-round, best September-April",
      regulations: "5 bass daily limit. No minimum size. Valid FL freshwater license required.",
      species: ["Largemouth Bass", "Black Crappie", "Bluegill", "Catfish"],
      amenities: ["Boat Ramps", "Marinas", "Guide Services", "RV Parks", "Bait Shops"],
      tags: ["bass fishing", "lake", "boat fishing", "trophy fish"],
      coordinates: { lat: 26.9467, lng: -80.8297 },
      metadata: { boat_access: "true", water_type: "freshwater lake", best_technique: "flipping grass" },
      isFeatured: false,
    },
    {
      type: "fishing",
      name: "Outer Banks Surf",
      location: "Nags Head, NC",
      state: "North Carolina",
      description: "Premier surf fishing destination along miles of undeveloped beaches. Excellent runs of red drum, bluefish, and flounder with beach driving access.",
      image: "/images/cat-fishing.jpg",
      rating: 4.5,
      reviews: 876,
      difficulty: "Moderate",
      season: "April-November",
      regulations: "Red drum slot 18-27 inches, 1 per day. NC coastal recreational fishing license required.",
      species: ["Red Drum", "Bluefish", "Flounder", "Speckled Trout", "Pompano"],
      amenities: ["Beach Access", "Tackle Shops", "4WD Beach Permits", "Campgrounds", "Pier Fishing"],
      tags: ["surf fishing", "beach", "red drum", "coastal"],
      coordinates: { lat: 35.9574, lng: -75.6241 },
      metadata: { boat_access: "false", water_type: "saltwater surf", best_technique: "surf casting" },
      isFeatured: false,
    },

    {
      type: "hunting",
      name: "Atchafalaya National Wildlife Refuge",
      location: "Krotz Springs, LA",
      state: "Louisiana",
      description: "Vast bottomland hardwood swamp ecosystem in the heart of the Atchafalaya Basin. Outstanding waterfowl hunting with flooded timber and marsh habitats.",
      image: "/images/cat-hunting.jpg",
      rating: 4.8,
      reviews: 654,
      difficulty: "Hard",
      season: "November-January (waterfowl), October-February (deer)",
      regulations: "Federal and state waterfowl stamps required. WMA permit needed. Steel shot only for waterfowl.",
      species: ["Mallard", "Wood Duck", "Teal", "White-tailed Deer", "Wild Turkey"],
      amenities: ["Boat Launches", "Public Blinds", "Campgrounds", "Check Stations"],
      tags: ["waterfowl", "swamp", "public land", "duck hunting"],
      coordinates: { lat: 30.5374, lng: -91.7429 },
      metadata: { land_type: "NWR", access_type: "boat", blind_type: "flooded timber" },
      isFeatured: true,
    },
    {
      type: "hunting",
      name: "Kaibab National Forest",
      location: "Fredonia, AZ",
      state: "Arizona",
      description: "North Kaibab unit renowned for trophy mule deer and elk hunting. Ponderosa pine and mixed conifer forests along the Grand Canyon's North Rim.",
      image: "/images/cat-hiking.jpg",
      rating: 4.85,
      reviews: 432,
      difficulty: "Hard",
      season: "October-November (rifle), August-September (archery)",
      regulations: "Draw-only tags for elk and mule deer. Hunter education required. Check unit-specific restrictions.",
      species: ["Mule Deer", "Elk", "Merriam's Turkey", "Mountain Lion"],
      amenities: ["Forest Roads", "Dispersed Camping", "Water Sources", "Trailheads"],
      tags: ["trophy mule deer", "elk", "national forest", "draw hunt"],
      coordinates: { lat: 36.7256, lng: -112.2166 },
      metadata: { land_type: "National Forest", access_type: "vehicle and foot", terrain: "mountainous" },
      isFeatured: true,
    },
    {
      type: "hunting",
      name: "Fort Stewart WMA",
      location: "Hinesville, GA",
      state: "Georgia",
      description: "Military installation with exceptional public hunting access on over 280,000 acres. Prime habitat for white-tailed deer, turkey, and small game.",
      image: "/images/cat-hunting.jpg",
      rating: 4.5,
      reviews: 567,
      difficulty: "Moderate",
      season: "September-February",
      regulations: "iSportsman registration required. Military installation access rules apply. GA hunting license and WMA stamp required.",
      species: ["White-tailed Deer", "Wild Turkey", "Feral Hog", "Dove", "Quail"],
      amenities: ["Managed Stands", "Check Stations", "Parking Areas", "Restrooms"],
      tags: ["WMA", "military land", "deer hunting", "public access"],
      coordinates: { lat: 31.8700, lng: -81.6100 },
      metadata: { land_type: "WMA/Military", access_type: "vehicle", registration: "iSportsman" },
      isFeatured: false,
    },
    {
      type: "hunting",
      name: "Theodore Roosevelt National Grasslands",
      location: "Dickinson, ND",
      state: "North Dakota",
      description: "Rolling mixed-grass prairies offering exceptional upland bird hunting. Miles of public grasslands with healthy populations of sharp-tailed grouse and pheasants.",
      image: "/images/cat-camping.jpg",
      rating: 4.6,
      reviews: 389,
      difficulty: "Moderate",
      season: "September-January",
      regulations: "ND small game license required. National Grassland hunting regulations apply. No lead shot for waterfowl.",
      species: ["Sharp-tailed Grouse", "Ring-necked Pheasant", "Hungarian Partridge", "Mule Deer", "Pronghorn"],
      amenities: ["Parking Areas", "Walk-in Access", "Campgrounds", "PLOTS Land Access"],
      tags: ["upland birds", "prairie", "public grassland", "walk-in hunting"],
      coordinates: { lat: 46.8967, lng: -103.5413 },
      metadata: { land_type: "National Grassland", access_type: "walk-in", terrain: "rolling prairie" },
      isFeatured: false,
    },
    {
      type: "hunting",
      name: "Black Hills National Forest",
      location: "Custer, SD",
      state: "South Dakota",
      description: "Mountainous pine forest in western South Dakota offering diverse big game hunting. Home to elk, mule deer, white-tailed deer, and mountain goats.",
      image: "/images/cat-hunting.jpg",
      rating: 4.7,
      reviews: 478,
      difficulty: "Hard",
      season: "September-November (archery and rifle)",
      regulations: "Draw tags for elk. Either-sex deer tags available OTC. SD hunting license required.",
      species: ["Elk", "Mule Deer", "White-tailed Deer", "Mountain Goat", "Merriam's Turkey"],
      amenities: ["Forest Roads", "Dispersed Camping", "Trailheads", "Water Sources", "Horse Camps"],
      tags: ["elk hunting", "national forest", "big game", "mountain hunting"],
      coordinates: { lat: 43.8554, lng: -103.4591 },
      metadata: { land_type: "National Forest", access_type: "vehicle and foot", terrain: "mountainous forest" },
      isFeatured: true,
    },
    {
      type: "hunting",
      name: "Green Swamp WMA",
      location: "Polk City, FL",
      state: "Florida",
      description: "Over 50,000 acres of cypress swamp and pine flatwoods in central Florida. Excellent deer, turkey, and hog hunting with year-round opportunities.",
      image: "/images/cat-hunting.jpg",
      rating: 4.4,
      reviews: 321,
      difficulty: "Moderate",
      season: "September-March",
      regulations: "FL hunting license and WMA permit required. Quota hunt permits for some seasons. Check area-specific rules.",
      species: ["White-tailed Deer", "Wild Turkey", "Feral Hog", "Osceola Turkey"],
      amenities: ["Check Stations", "Campgrounds", "ATV Trails", "Parking Areas"],
      tags: ["WMA", "swamp hunting", "hog hunting", "turkey hunting"],
      coordinates: { lat: 28.3800, lng: -81.9300 },
      metadata: { land_type: "WMA", access_type: "vehicle and ATV", terrain: "swamp and flatwoods" },
      isFeatured: false,
    },

    {
      type: "climbing",
      name: "Red River Gorge",
      location: "Slade, KY",
      state: "Kentucky",
      description: "World-class sport climbing destination with over 3,000 routes on stunning sandstone cliffs. Steep overhanging walls with incredible pocket pulling and technical face climbing.",
      image: "/images/cat-rock-climbing.jpg",
      rating: 4.9,
      reviews: 2341,
      difficulty: "Moderate to Expert",
      season: "March-November, best in fall",
      regulations: "Respect fixed anchors. No new bolting without permission. Follow Leave No Trace principles. Some areas on private land require access fees.",
      species: ["Sport", "Trad", "Bouldering", "Top Rope"],
      amenities: ["Campgrounds", "Gear Shops", "Guide Services", "Restaurants", "Showers"],
      tags: ["sport climbing", "sandstone", "overhangs", "world class"],
      coordinates: { lat: 37.7750, lng: -83.6700 },
      metadata: { grade: "5.6-5.14d", rock_type: "sandstone", route_count: "3000+", style: "sport" },
      isFeatured: true,
    },
    {
      type: "climbing",
      name: "Joshua Tree National Park",
      location: "Twentynine Palms, CA",
      state: "California",
      description: "Iconic desert climbing on unique monzogranite formations. Thousands of routes ranging from beginner slabs to multi-pitch trad classics amid stunning desert landscape.",
      image: "/images/cat-rock-climbing.jpg",
      rating: 4.85,
      reviews: 1987,
      difficulty: "Easy to Hard",
      season: "October-April",
      regulations: "National Park entrance fee required. No fixed anchors without NPS approval. Camping reservations needed in season.",
      species: ["Trad", "Sport", "Bouldering", "Top Rope", "Multi-pitch"],
      amenities: ["Campgrounds", "Visitor Center", "Guide Services", "Gear Rental"],
      tags: ["trad climbing", "desert", "monzogranite", "multi-pitch"],
      coordinates: { lat: 33.8734, lng: -115.9010 },
      metadata: { grade: "5.0-5.13", rock_type: "monzogranite", route_count: "8000+", style: "trad" },
      isFeatured: true,
    },
    {
      type: "climbing",
      name: "Hueco Tanks State Park",
      location: "El Paso, TX",
      state: "Texas",
      description: "Legendary bouldering destination featuring world-class problems on syenite rock. Home to iconic problems and pictograph-covered caves in the Chihuahuan Desert.",
      image: "/images/cat-climbing.jpg",
      rating: 4.8,
      reviews: 1245,
      difficulty: "Moderate to Expert",
      season: "October-March",
      regulations: "Daily visitor limits enforced. Reservations required. Guide required for North Mountain. No chalk on pictographs.",
      species: ["Bouldering", "Sport", "Top Rope"],
      amenities: ["Campgrounds", "Restrooms", "Guide Services", "Water Stations"],
      tags: ["bouldering", "syenite", "desert", "world class"],
      coordinates: { lat: 31.9191, lng: -106.0411 },
      metadata: { grade: "V0-V15", rock_type: "syenite", route_count: "2000+", style: "bouldering" },
      isFeatured: true,
    },
    {
      type: "climbing",
      name: "Rumney Rocks",
      location: "Rumney, NH",
      state: "New Hampshire",
      description: "Premier sport climbing crag in New England with over 300 routes on metamorphic schist. Excellent variety from beginner-friendly to cutting-edge difficulty.",
      image: "/images/cat-rock-climbing.jpg",
      rating: 4.7,
      reviews: 876,
      difficulty: "Easy to Hard",
      season: "April-November",
      regulations: "Stay on marked trails. No new routes without Rumney Climbers Association approval. Dogs must be leashed.",
      species: ["Sport", "Top Rope"],
      amenities: ["Parking", "Trail Access", "Nearby Camping", "Gear Shops"],
      tags: ["sport climbing", "schist", "new england", "beginner friendly"],
      coordinates: { lat: 43.8052, lng: -71.8125 },
      metadata: { grade: "5.4-5.14b", rock_type: "schist", route_count: "300+", style: "sport" },
      isFeatured: false,
    },
    {
      type: "climbing",
      name: "Smith Rock State Park",
      location: "Terrebonne, OR",
      state: "Oregon",
      description: "Birthplace of American sport climbing with iconic routes on welded tuff and basalt towers. Stunning Crooked River canyon setting with hundreds of classic lines.",
      image: "/images/cat-climbing.jpg",
      rating: 4.9,
      reviews: 1654,
      difficulty: "Easy to Expert",
      season: "March-November, best spring and fall",
      regulations: "State park day-use fee required. Bivouac camping area available. Dogs must be leashed. Seasonal raptor closures.",
      species: ["Sport", "Trad", "Multi-pitch", "Bouldering"],
      amenities: ["Campground", "Restrooms", "Water", "Trails", "Guide Services"],
      tags: ["sport climbing", "tuff", "classic routes", "birthplace of sport climbing"],
      coordinates: { lat: 44.3682, lng: -121.1426 },
      metadata: { grade: "5.5-5.14c", rock_type: "welded tuff", route_count: "1800+", style: "sport and trad" },
      isFeatured: false,
    },
    {
      type: "climbing",
      name: "New River Gorge",
      location: "Fayetteville, WV",
      state: "West Virginia",
      description: "East Coast climbing mecca with over 1,700 routes on bullet-hard Nuttall Sandstone. Steep, athletic climbing with incredible exposure above the New River.",
      image: "/images/cat-rock-climbing.jpg",
      rating: 4.85,
      reviews: 1432,
      difficulty: "Moderate to Expert",
      season: "March-November",
      regulations: "National Park and Preserve rules apply. Some areas require approach from designated trails. Leave No Trace principles.",
      species: ["Sport", "Trad", "Bouldering", "Top Rope"],
      amenities: ["Campgrounds", "Gear Shops", "Guide Services", "Restaurants", "Visitor Center"],
      tags: ["sport climbing", "trad climbing", "sandstone", "national park"],
      coordinates: { lat: 38.0659, lng: -81.0787 },
      metadata: { grade: "5.5-5.14a", rock_type: "Nuttall sandstone", route_count: "1700+", style: "sport and trad" },
      isFeatured: false,
    },

    {
      type: "public_lands",
      name: "Yellowstone National Park",
      location: "Yellowstone, WY",
      state: "Wyoming",
      description: "America's first national park spanning over 2.2 million acres of geothermal wonders, wildlife, and pristine wilderness. Home to Old Faithful, Grand Prismatic Spring, and the largest concentration of geysers on Earth.",
      image: "/images/cat-hiking.jpg",
      rating: 4.9,
      reviews: 12453,
      difficulty: null,
      season: "Year-round, some roads closed November-April",
      regulations: "NPS entrance fee required. Backcountry permits for overnight stays. Stay 100 yards from bears and wolves, 25 yards from other wildlife.",
      species: null,
      amenities: ["Visitor Centers", "Campgrounds", "Lodges", "Restaurants", "General Stores", "Ranger Programs", "Shuttle Service"],
      tags: ["national park", "geysers", "wildlife", "wilderness", "iconic"],
      coordinates: { lat: 44.4280, lng: -110.5885 },
      metadata: { designation: "National Park", acreage: "2219791", established: "1872", managing_agency: "NPS" },
      isFeatured: true,
    },
    {
      type: "public_lands",
      name: "Boundary Waters Canoe Area Wilderness",
      location: "Ely, MN",
      state: "Minnesota",
      description: "Over one million acres of pristine lakes, rivers, and boreal forest along the Canadian border. Premier paddling and fishing destination with over 1,200 miles of canoe routes.",
      image: "/images/cat-water-sports.jpg",
      rating: 4.85,
      reviews: 4321,
      difficulty: null,
      season: "May-September for paddling, year-round access",
      regulations: "Wilderness permits required May-September. Group size limits. No motors in most areas. Bear canisters required.",
      species: null,
      amenities: ["Entry Points", "Portage Trails", "Designated Campsites", "Outfitters", "Ranger Stations"],
      tags: ["wilderness", "canoeing", "fishing", "boreal forest", "pristine"],
      coordinates: { lat: 48.0833, lng: -91.8333 },
      metadata: { designation: "Wilderness Area", acreage: "1090000", established: "1978", managing_agency: "USFS" },
      isFeatured: true,
    },
    {
      type: "public_lands",
      name: "Custer Gallatin National Forest",
      location: "Bozeman, MT",
      state: "Montana",
      description: "3.1 million acres of diverse landscapes from alpine peaks to rolling grasslands. Gateway to Yellowstone with exceptional hiking, fishing, hunting, and winter recreation.",
      image: "/images/cat-camping.jpg",
      rating: 4.7,
      reviews: 2876,
      difficulty: null,
      season: "Year-round",
      regulations: "Forest Service regulations apply. Campfire permits may be required. Check current fire restrictions. Some trails require stock use permits.",
      species: null,
      amenities: ["Campgrounds", "Trailheads", "Ranger Stations", "Boat Ramps", "Picnic Areas", "Horse Camps"],
      tags: ["national forest", "hiking", "fishing", "hunting", "mountain recreation"],
      coordinates: { lat: 45.6833, lng: -110.4000 },
      metadata: { designation: "National Forest", acreage: "3100000", established: "2014", managing_agency: "USFS" },
      isFeatured: false,
    },
    {
      type: "public_lands",
      name: "Grand Staircase-Escalante National Monument",
      location: "Escalante, UT",
      state: "Utah",
      description: "Nearly 1.9 million acres of rugged canyon country with slot canyons, natural bridges, and vast wilderness. One of the last places in the continental US to be mapped.",
      image: "/images/cat-hiking.jpg",
      rating: 4.8,
      reviews: 3456,
      difficulty: null,
      season: "March-November, avoid summer heat",
      regulations: "BLM permit required for overnight backpacking in certain areas. High-clearance vehicles recommended. Check road conditions before travel.",
      species: null,
      amenities: ["Visitor Centers", "Dispersed Camping", "Trailheads", "Scenic Drives"],
      tags: ["BLM", "canyon country", "slot canyons", "wilderness", "remote"],
      coordinates: { lat: 37.3861, lng: -111.4356 },
      metadata: { designation: "National Monument (BLM)", acreage: "1870000", established: "1996", managing_agency: "BLM" },
      isFeatured: true,
    },
    {
      type: "public_lands",
      name: "Adirondack Park",
      location: "Lake Placid, NY",
      state: "New York",
      description: "The largest publicly protected area in the contiguous US at 6 million acres. Mix of public and private land featuring 46 High Peaks, thousands of lakes, and vast forests.",
      image: "/images/cat-mountain-biking.jpg",
      rating: 4.75,
      reviews: 5678,
      difficulty: null,
      season: "Year-round",
      regulations: "DEC regulations apply. Bear canisters required in Eastern High Peaks. Permits for some trailheads during peak season.",
      species: null,
      amenities: ["Campgrounds", "Lean-tos", "Visitor Centers", "Boat Launches", "Ski Areas", "Trailheads"],
      tags: ["state park", "high peaks", "lakes", "four season", "hiking"],
      coordinates: { lat: 44.1126, lng: -74.0404 },
      metadata: { designation: "State Park/Forest Preserve", acreage: "6100000", established: "1892", managing_agency: "NYS DEC" },
      isFeatured: false,
    },
    {
      type: "public_lands",
      name: "Ocala National Forest",
      location: "Silver Springs, FL",
      state: "Florida",
      description: "The southernmost national forest in the continental US featuring sand pine scrub, freshwater springs, and subtropical wilderness. Year-round recreation in a unique ecosystem.",
      image: "/images/cat-electric-mobility.jpg",
      rating: 4.5,
      reviews: 2134,
      difficulty: null,
      season: "Year-round, best October-April",
      regulations: "Forest Service regulations. Campfire permits required. Swimming at own risk at springs. OHV permits for designated trails.",
      species: null,
      amenities: ["Campgrounds", "Springs", "Swimming Areas", "OHV Trails", "Boat Ramps", "Picnic Areas"],
      tags: ["national forest", "springs", "subtropical", "OHV", "swimming"],
      coordinates: { lat: 29.1900, lng: -81.6500 },
      metadata: { designation: "National Forest", acreage: "607000", established: "1908", managing_agency: "USFS" },
      isFeatured: false,
    },
    {
      type: "public_lands",
      name: "Big Bend National Park",
      location: "Big Bend, TX",
      state: "Texas",
      description: "Over 800,000 acres of Chihuahuan Desert wilderness along the Rio Grande. Dramatic canyons, desert mountains, and some of the darkest night skies in North America.",
      image: "/images/cat-winter-sports.jpg",
      rating: 4.8,
      reviews: 3890,
      difficulty: null,
      season: "October-April, summers extremely hot",
      regulations: "NPS entrance fee. Backcountry permits required. No collecting rocks, plants, or artifacts. Border crossing restrictions.",
      species: null,
      amenities: ["Visitor Centers", "Campgrounds", "Lodge", "River Access", "Hot Springs", "Ranger Programs"],
      tags: ["national park", "desert", "dark skies", "river", "remote"],
      coordinates: { lat: 29.2498, lng: -103.2502 },
      metadata: { designation: "National Park", acreage: "801163", established: "1944", managing_agency: "NPS" },
      isFeatured: true,
    },
    {
      type: "public_lands",
      name: "Pisgah National Forest",
      location: "Brevard, NC",
      state: "North Carolina",
      description: "Over 500,000 acres of lush Appalachian forest with stunning waterfalls, the Blue Ridge Parkway, and legendary mountain biking trails. Birthplace of modern forestry in America.",
      image: "/images/cat-mountain-biking.jpg",
      rating: 4.7,
      reviews: 3210,
      difficulty: null,
      season: "Year-round",
      regulations: "Forest Service regulations apply. Hunting in designated areas with valid license. Campfire restrictions during dry periods.",
      species: null,
      amenities: ["Campgrounds", "Trailheads", "Waterfalls", "Swimming Holes", "Mountain Biking Trails", "Ranger Station"],
      tags: ["national forest", "waterfalls", "mountain biking", "appalachian", "forestry"],
      coordinates: { lat: 35.3167, lng: -82.7333 },
      metadata: { designation: "National Forest", acreage: "512758", established: "1916", managing_agency: "USFS" },
      isFeatured: false,
    },
  ]);

  console.log("Activity locations seeded successfully!");
}

seed()
  .then(() => seedActivityLocations())
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Seed error:", err);
    process.exit(1);
  });
