import { db } from "./db";
import { catalogLocations } from "@shared/schema";
import { eq, and } from "drizzle-orm";

const U = (id: string) => `https://images.unsplash.com/${id}?w=800&h=600&fit=crop`;

const TN_PARKS = [U("photo-1506905925346-21bda4d32df4"), U("photo-1472396961693-142e6e269027"), U("photo-1464822759023-fed622ff2c3b")];
const TN_FALLS = [U("photo-1432405972618-c6b0cfba8428"), U("photo-1546182990-dffeafbe841d"), U("photo-1501594907352-04cda38ebc29")];
const TN_FOREST = [U("photo-1441974231531-c6227db76b6e"), U("photo-1448375240586-882707db888b"), U("photo-1473448912268-2022ce9509d8")];
const TN_LAKE = [U("photo-1544551763-77ef2d0cfc6c"), U("photo-1501594907352-04cda38ebc29"), U("photo-1506477331477-33d5d8b3dc85")];
const TN_MTN = [U("photo-1469474968028-56623f02e42e"), U("photo-1414609245224-afa02bfb3fda"), U("photo-1518173946687-a8bfc1b7e6f7")];
const TN_TRAIL = [U("photo-1551632811-561732d1e306"), U("photo-1504280390367-361c6d9f38f4"), U("photo-1537225228614-56cc3556d7ed")];
const TN_CAVE = [U("photo-1504280390367-361c6d9f38f4"), U("photo-1478131143081-80f7f84ca84d"), U("photo-1544191696-102dbdaeeaa0")];
const TN_RIVER = [U("photo-1517824806704-9040b037703b"), U("photo-1544551763-46a013bb70d5"), U("photo-1504309092620-4d0ec726efa4")];

function img(arr: string[], i: number) { return arr[i % arr.length]; }

export const tennesseeLocations = [
  // ===== TENNESSEE STATE PARKS =====
  {
    name: "Cedars of Lebanon State Park",
    slug: "cedars-of-lebanon-state-park",
    type: "state_park",
    description: "Nestled in the heart of Wilson County, Cedars of Lebanon State Park preserves one of the largest remaining red cedar forests in the United States — a living relic of the vast cedar glades that once blanketed Middle Tennessee's limestone basin. Across 900 acres of fragrant cedar woodland and rare limestone glade ecosystems, visitors discover a landscape unlike anywhere else in the Southeast. The park's cedar glades harbor dozens of plant species found nowhere else on Earth, including the Tennessee coneflower, once thought extinct and now a celebrated conservation success story. Miles of trails wind through cathedral-like groves where ancient Eastern red cedars stand sentinel over carpets of limestone fern and glade wildflowers. The park's eight miles of hiking trails range from gentle woodland strolls to immersive backcountry loops, while the Dixon Merritt Nature Trail offers an accessible introduction to glade ecology. A spring-fed swimming pool, horseback riding trails, and well-appointed cabins make this a year-round destination for families and nature enthusiasts alike. The surrounding cedar forest teems with wild turkey, white-tailed deer, and a remarkable diversity of songbirds, while the limestone glows golden in late afternoon light — a photographer's paradise in every season.",
    editorialSummary: "One of America's largest remaining red cedar forests, protecting globally rare limestone glade ecosystems found nowhere else on Earth.",
    address: "328 Cedar Forest Rd",
    city: "Lebanon",
    state: "TN",
    zipCode: "37090",
    lat: 36.0853,
    lng: -86.3314,
    activities: ["hiking", "camping", "horseback riding", "swimming", "disc golf", "mountain biking", "wildlife viewing", "photography"],
    species: ["eastern red cedar", "Tennessee coneflower", "limestone fame flower", "white-tailed deer", "wild turkey", "eastern box turtle", "pileated woodpecker", "cedar glade St. John's wort"],
    gameTypes: null,
    amenities: ["cabins", "camping", "restrooms", "trails", "swimming pool", "picnic shelters", "playground", "horse stables", "disc golf course", "nature center"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["cedar forest", "limestone glades", "endemic species", "Tennessee coneflower", "horseback riding", "family friendly", "Wilson County"],
    difficulty: "easy",
    regulations: "No entrance fee. Cabin and campsite reservations available online. Pets allowed on leash in designated areas. No foraging of rare glade plants — many are federally protected. Horseback riding on designated trails only.",
    website: "https://tnstateparks.com/parks/cedars-of-lebanon",
    phone: "(615) 443-2769",
    bookingUrl: "https://reserve.tnstateparks.com",
    permitUrl: null,
    imageUrl: img(TN_FOREST, 0),
    photos: [img(TN_FOREST, 0), img(TN_TRAIL, 0), img(TN_FOREST, 2)],
    rating: 4.6,
    reviews: 2847,
    priceRange: "$",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: true,
    isVerified: true,
    metadata: {
      acreage: 900,
      knownFor: "Largest remaining Eastern red cedar forest in the US with globally rare limestone glade ecosystems",
      foraging: {
        permitted: "Limited — surrounding areas outside park boundaries offer seasonal foraging opportunities",
        springEdibles: ["ramps (wild leeks) in nearby woodlands", "dandelion greens", "wild violets", "chickweed"],
        summerEdibles: ["blackberries along forest edges", "wild black raspberries", "wood sorrel", "elderberries"],
        fallEdibles: ["persimmons along roadsides", "black walnuts", "hickory nuts", "pawpaws along creek bottoms"],
        mushrooms: ["morels near dead elms (spring)", "chanterelles in oak-cedar mix (summer)", "chicken of the woods on dead hardwoods"],
        caution: "Tennessee coneflower and other glade endemics are federally protected — never harvest plants from the limestone glades. Foraging is restricted within state park boundaries."
      },
      historicalNote: "Named by early settlers who compared the dense cedar forests to the biblical cedars of Lebanon. The Civilian Conservation Corps built many of the park's original structures in the 1930s."
    },
  },
  {
    name: "South Cumberland State Park",
    slug: "south-cumberland-state-park",
    type: "state_park",
    description: "Sprawling across more than 30,000 acres of the Cumberland Plateau's rugged eastern escarpment, South Cumberland State Park is Tennessee's largest and most wild state park — a vast mosaic of sandstone gorges, primeval hemlock forests, and thundering waterfalls that rivals any landscape in the Appalachian chain. The park's crown jewel is the legendary Fiery Gizzard Trail, consistently ranked among the top hiking trails in America, a punishing 12.5-mile odyssey through boulder fields, past crystal swimming holes, and along knife-edge ridgelines with views stretching to the distant Smokies. Foster Falls plunges 60 feet into a natural amphitheater of moss-draped stone, drawing rock climbers from across the nation to its overhanging sandstone walls. Grundy Forest's old-growth hemlocks tower above a labyrinth of cascading creeks, while Savage Gulf's 55-foot Stone Door provides a dramatic portal into one of the deepest gorges east of the Mississippi. This is Tennessee at its most untamed — a landscape of cathedral forests, rare salamanders, and silence so deep you can hear the mountain breathe.",
    editorialSummary: "Tennessee's largest state park, featuring the legendary Fiery Gizzard Trail, Foster Falls, and some of the deepest gorges east of the Mississippi.",
    address: "11745 US-41",
    city: "Monteagle",
    state: "TN",
    zipCode: "37356",
    lat: 35.2384,
    lng: -85.9189,
    activities: ["hiking", "rock climbing", "backpacking", "swimming", "rappelling", "photography", "wildlife viewing", "mountain biking"],
    species: ["eastern hemlock", "Cumberland rosinweed", "green salamander", "timber rattlesnake", "cerulean warbler", "Virginia big-eared bat", "black bear", "peregrine falcon"],
    gameTypes: null,
    amenities: ["visitor center", "camping", "backcountry camping", "restrooms", "trails", "picnic areas", "ranger station"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["fiery gizzard", "foster falls", "savage gulf", "stone door", "rock climbing", "gorges", "waterfalls", "backcountry"],
    difficulty: "hard",
    regulations: "Backcountry permits required for overnight camping. Stay on marked trails in gorge areas. Rock climbing requires registration at Foster Falls. No rappelling into Savage Gulf without permit.",
    website: "https://tnstateparks.com/parks/south-cumberland",
    phone: "(931) 924-2980",
    bookingUrl: "https://reserve.tnstateparks.com",
    permitUrl: "https://tnstateparks.com/parks/south-cumberland",
    imageUrl: img(TN_FALLS, 0),
    photos: [img(TN_FALLS, 0), img(TN_FOREST, 1), img(TN_MTN, 0)],
    rating: 4.9,
    reviews: 6234,
    priceRange: "$",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: true,
    isVerified: true,
    metadata: {
      acreage: 30845,
      knownFor: "Fiery Gizzard Trail (top-rated US hiking), Foster Falls rock climbing, Savage Gulf gorges, Stone Door overlook",
      foraging: {
        permitted: "Restricted within park — surrounding Cumberland Plateau areas are rich foraging territory",
        springEdibles: ["ramps in cove hardwood forests", "toothwort", "spring beauty corms", "wild ginger"],
        summerEdibles: ["blackberries along trail edges", "serviceberries", "wild blueberries on plateau ridges", "wood sorrel"],
        fallEdibles: ["pawpaws in gulf bottoms", "persimmons", "black walnuts", "chinquapin nuts"],
        mushrooms: ["morels near tulip poplar and ash (spring)", "chanterelles in oak forests (summer)", "black trumpets in beech groves", "hen of the woods (fall)"],
        caution: "Gorge walls are ecologically sensitive. Many rare and endemic plant species are protected. Foraging within park boundaries is restricted."
      }
    },
  },
  {
    name: "Burgess Falls State Park",
    slug: "burgess-falls-state-park",
    type: "state_park",
    description: "Few parks in the American South deliver such concentrated natural drama as Burgess Falls, where the Falling Water River descends through a succession of four increasingly spectacular waterfalls over the course of a single mile-and-a-half trail. The journey begins gently, with a broad cascade shimmering over ledges of ancient limestone, then builds to a crescendo at the park's namesake — a breathtaking 136-foot curtain of whitewater thundering into a turquoise plunge pool carved from 300-million-year-old rock. The trail hugs the river's edge through a corridor of towering tulip poplars, sycamores, and hemlocks, with each bend revealing a new cascade more dramatic than the last. Spring brings carpets of trillium and bloodroot to the forest floor, while autumn transforms the gorge into a gallery of scarlet and gold reflected in the emerald pools below. A designated State Natural Area, Burgess Falls protects one of Middle Tennessee's most pristine riverine ecosystems — a sanctuary for great blue herons, belted kingfishers, and the occasional river otter spotted playing in the pools beneath the falls.",
    editorialSummary: "A dramatic mile-long trail past four successive waterfalls culminating in a thundering 136-foot cascade into a turquoise gorge.",
    address: "8559 Burgess Falls Dr",
    city: "Sparta",
    state: "TN",
    zipCode: "38583",
    lat: 36.0447,
    lng: -85.5936,
    activities: ["hiking", "photography", "wildlife viewing", "fishing", "kayaking"],
    species: ["great blue heron", "belted kingfisher", "river otter", "smallmouth bass", "tulip poplar", "eastern hemlock", "trillium", "bloodroot"],
    gameTypes: null,
    amenities: ["restrooms", "trails", "picnic areas", "parking", "interpretive signs"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["waterfalls", "gorge", "photography", "short hike", "family friendly", "swimming holes"],
    difficulty: "moderate",
    regulations: "No entrance fee. Trail to base of falls involves steep stairs — use caution. Swimming at your own risk. No cliff jumping. Pets on leash allowed.",
    website: "https://tnstateparks.com/parks/burgess-falls",
    phone: "(931) 432-5312",
    bookingUrl: null,
    permitUrl: null,
    imageUrl: img(TN_FALLS, 1),
    photos: [img(TN_FALLS, 1), img(TN_FALLS, 0), img(TN_RIVER, 0)],
    rating: 4.8,
    reviews: 8912,
    priceRange: "Free",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: true,
    isVerified: true,
    metadata: {
      acreage: 375,
      knownFor: "Four successive waterfalls including the spectacular 136-foot main falls, one of Tennessee's most photographed natural landmarks",
      foraging: {
        permitted: "Restricted within State Natural Area boundaries",
        springEdibles: ["wild violets along trail", "chickweed", "dandelion greens in meadow areas"],
        summerEdibles: ["blackberries along forest edges", "elderberries near water"],
        fallEdibles: ["persimmons in surrounding areas", "black walnuts"],
        mushrooms: ["oyster mushrooms on fallen hardwoods", "turkey tail (medicinal)"],
        caution: "This is a State Natural Area — harvesting plants is prohibited within park boundaries."
      }
    },
  },
  {
    name: "Radnor Lake State Park",
    slug: "radnor-lake-state-park",
    type: "state_park",
    description: "An emerald oasis just six miles from the honky-tonks of Broadway, Radnor Lake State Park stands as living proof that true wilderness can thrive within earshot of a major American city. This 1,368-acre State Natural Area cradles an 85-acre lake in a bowl of forested hills where white-tailed deer step delicately through morning mist, great horned owls call from century-old oaks, and wild turkeys strut along trails mere minutes from Nashville's skyline. The lake was originally impounded in 1914 by the Louisville & Nashville Railroad to provide water for steam engines, and the surrounding forest has been regenerating into mature hardwood woodland ever since. Today, six miles of trails loop through a tapestry of upland oak-hickory forest, cedar glades, and lakeshore wetlands that support over 240 species of birds — making Radnor one of the premier birding destinations in the interior Southeast. The park's strict protections — no jogging, no pets, no bicycles, no swimming — create an atmosphere of contemplative stillness rare in modern America. At dawn, when fog lifts off the lake and a barred owl's call echoes through the hollow, Nashville feels a thousand miles away.",
    editorialSummary: "Nashville's crown jewel of urban wilderness — a serene lake sanctuary harboring 240+ bird species just minutes from downtown.",
    address: "1160 Otter Creek Rd",
    city: "Nashville",
    state: "TN",
    zipCode: "37220",
    lat: 36.0631,
    lng: -86.8087,
    activities: ["hiking", "wildlife viewing", "birding", "photography", "nature study"],
    species: ["great horned owl", "barred owl", "white-tailed deer", "wild turkey", "great blue heron", "green heron", "red-shouldered hawk", "mink", "beaver", "wood duck"],
    gameTypes: null,
    amenities: ["visitor center", "restrooms", "trails", "nature center", "interpretive programs", "parking"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["birding", "urban wilderness", "Nashville", "serene", "nature photography", "accessible"],
    difficulty: "easy",
    regulations: "No entrance fee. No pets, bicycles, jogging, or swimming. Walking and hiking only. Gates close at sunset. Photography tripods allowed on designated trails only.",
    website: "https://tnstateparks.com/parks/radnor-lake",
    phone: "(615) 373-3467",
    bookingUrl: null,
    permitUrl: null,
    imageUrl: img(TN_LAKE, 0),
    photos: [img(TN_LAKE, 0), img(TN_FOREST, 0), img(TN_LAKE, 2)],
    rating: 4.9,
    reviews: 12453,
    priceRange: "Free",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: true,
    isVerified: true,
    metadata: {
      acreage: 1368,
      knownFor: "Premier urban wilderness and birding destination with 240+ bird species, just 6 miles from downtown Nashville",
      foraging: {
        permitted: "Prohibited — Radnor Lake is a Class II State Natural Area with strict no-harvest protections",
        notableFlora: ["spring ephemeral wildflowers (trillium, bloodroot, hepatica)", "native orchids", "cardinal flower along lakeshore"],
        caution: "All plants, fungi, and natural materials are fully protected. This is an observation-only natural area."
      }
    },
  },
  {
    name: "Roan Mountain State Park",
    slug: "roan-mountain-state-park",
    type: "state_park",
    description: "Rising to 6,285 feet along the Tennessee-North Carolina border, the Roan Highlands are among the most botanically spectacular mountains in eastern North America — and Roan Mountain State Park provides the gateway to this extraordinary landscape. Each June, the world's largest natural rhododendron garden erupts into bloom across 600 acres of mountainside, painting the high balds in swaths of pink and magenta that have drawn pilgrims since the days when a grand resort hotel graced the summit in the 1880s. But Roan Mountain's wonders extend far beyond rhododendron season. The park's grassy balds — mysterious treeless meadows whose origins still puzzle scientists — offer 360-degree panoramas stretching from Mount Mitchell to the Virginia highlands, while rare spruce-fir forests cloak the upper elevations in a boreal ecosystem more typical of Canada than the American South. The 2,006-acre park at the mountain's base wraps around the headwaters of the Doe River, where native brook trout flash in pools shaded by old-growth hemlocks. Winter brings crystalline hoarfrost and snow-covered balds that rival any alpine scene on the continent, while spring carpets the forest floor in a procession of wildflowers — trout lily, bloodroot, and the rare Gray's lily, found only in these mountains.",
    editorialSummary: "Gateway to the highest peaks on the Tennessee-North Carolina border, home to the world's largest natural rhododendron garden and mysterious grassy balds.",
    address: "527 Hwy 143",
    city: "Roan Mountain",
    state: "TN",
    zipCode: "37687",
    lat: 36.1613,
    lng: -82.1046,
    activities: ["hiking", "camping", "backpacking", "cross-country skiing", "wildlife viewing", "photography", "fishing", "wildflower viewing"],
    species: ["Catawba rhododendron", "Gray's lily", "spruce-fir forest", "northern saw-whet owl", "raven", "brook trout", "Carolina northern flying squirrel", "flame azalea"],
    gameTypes: null,
    amenities: ["cabins", "camping", "restrooms", "trails", "visitor center", "swimming pool", "playground", "picnic areas"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["rhododendron", "grassy balds", "high elevation", "wildflowers", "Appalachian Trail", "spruce-fir forest"],
    difficulty: "moderate",
    regulations: "No entrance fee. Backcountry camping by permit on Appalachian Trail. Weather changes rapidly at summit — come prepared. Rhododendron Gardens managed by US Forest Service.",
    website: "https://tnstateparks.com/parks/roan-mountain",
    phone: "(423) 772-0190",
    bookingUrl: "https://reserve.tnstateparks.com",
    permitUrl: null,
    imageUrl: img(TN_MTN, 0),
    photos: [img(TN_MTN, 0), img(TN_FOREST, 1), img(TN_MTN, 2)],
    rating: 4.8,
    reviews: 4567,
    priceRange: "$",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: true,
    isVerified: true,
    metadata: {
      acreage: 2006,
      knownFor: "World's largest natural rhododendron garden (600 acres), mysterious grassy balds, rare spruce-fir forest, Appalachian Trail access",
      foraging: {
        permitted: "Limited within park — Cherokee National Forest lands nearby offer foraging opportunities with permit",
        springEdibles: ["ramps in cove hardwood forests (abundant in Southern Appalachians)", "toothwort", "wild leeks", "spring beauty"],
        summerEdibles: ["wild blueberries on high balds", "blackberries", "serviceberries at elevation", "wood sorrel"],
        fallEdibles: ["American chestnuts (blight-resistant survivors)", "black walnuts at lower elevations", "hickory nuts"],
        mushrooms: ["morels at lower elevations (spring)", "chanterelles in mixed hardwood (summer)", "hen of the woods on old oaks (fall)", "black trumpets in beech forests"],
        caution: "Gray's lily and other rare alpine plants are protected. Foraging in Cherokee National Forest requires permit; ginseng harvest strictly regulated (Sept 16-30 only, limited permits)."
      }
    },
  },
  {
    name: "Reelfoot Lake State Park",
    slug: "reelfoot-lake-state-park",
    type: "state_park",
    description: "Born of catastrophe and now a cradle of extraordinary life, Reelfoot Lake is Tennessee's only natural lake — created in the winter of 1811-1812 when a series of massive earthquakes along the New Madrid Fault caused the Mississippi River to run backward and the land to sink, filling a vast depression with water. Today, this 15,000-acre shallow lake is a flooded forest of ghostly bald cypress trees draped in Spanish moss, their ancient knees rising from tea-dark water like sentinels of a drowned world. From December through March, Reelfoot becomes the winter home of one of the largest concentrations of American bald eagles in the interior United States, drawing thousands of visitors for ranger-led eagle tours aboard heated pontoon boats. The lake's labyrinthine channels harbor some of the finest crappie and bluegill fishing in the nation, while its marshes and mudflats support vast colonies of wading birds — great blue herons, great egrets, and the occasional American white pelican wheeling overhead in spiraling flocks. At sunset, when the cypress silhouettes blaze against a crimson sky and a bald eagle glides to its roost on silent wings, Reelfoot Lake feels less like a place and more like a vision from another century.",
    editorialSummary: "Tennessee's only natural lake, born from the 1811 earthquakes that reversed the Mississippi, now a bald eagle sanctuary and cypress swamp wonderland.",
    address: "2595 Hwy 21 E",
    city: "Tiptonville",
    state: "TN",
    zipCode: "38079",
    lat: 36.3520,
    lng: -89.4130,
    activities: ["fishing", "birding", "wildlife viewing", "boating", "kayaking", "photography", "eagle tours", "camping"],
    species: ["bald eagle", "bald cypress", "great blue heron", "great egret", "American white pelican", "crappie", "bluegill", "largemouth bass", "barred owl", "river otter"],
    gameTypes: ["crappie", "bluegill", "largemouth bass", "catfish"],
    amenities: ["cabins", "camping", "restrooms", "visitor center", "boat ramp", "boat rentals", "nature center", "gift shop", "eagle tour boats", "fish cleaning station"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["bald eagles", "cypress swamp", "earthquake lake", "fishing", "birding", "winter eagles", "West Tennessee"],
    difficulty: "easy",
    regulations: "No entrance fee. Fishing license required. Eagle tour reservations strongly recommended (December-March). Boat speed limits enforced. No wake zones in cypress areas.",
    website: "https://tnstateparks.com/parks/reelfoot-lake",
    phone: "(731) 253-9652",
    bookingUrl: "https://reserve.tnstateparks.com",
    permitUrl: null,
    imageUrl: img(TN_LAKE, 1),
    photos: [img(TN_LAKE, 1), img(TN_FOREST, 0), img(TN_LAKE, 2)],
    rating: 4.7,
    reviews: 5123,
    priceRange: "$",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: true,
    isVerified: true,
    metadata: {
      acreage: 25000,
      knownFor: "Tennessee's only natural lake created by the 1811 New Madrid earthquakes, winter bald eagle concentration, world-class crappie fishing, flooded cypress forest",
      foraging: {
        permitted: "Limited — some foraging in surrounding areas; check regulations",
        springEdibles: ["dandelion greens in meadows", "wild garlic", "cattail shoots along lake margins", "chickweed"],
        summerEdibles: ["blackberries", "mulberries (abundant in West TN)", "elderberries along lake edges", "wild plums"],
        fallEdibles: ["persimmons (prolific in West Tennessee)", "pecans", "black walnuts", "muscadines"],
        mushrooms: ["oyster mushrooms on fallen cypress and hardwoods", "morels near dead elms (spring)", "chicken of the woods"],
        caution: "Lake levels fluctuate. Foraging from boats requires caution. Cypress swamp areas may be difficult to navigate on foot."
      },
      historicalNote: "Created when the New Madrid earthquakes of 1811-1812 — the most powerful earthquakes in recorded North American history — caused the land to drop 5-20 feet and the Mississippi River to temporarily flow backward."
    },
  },
  {
    name: "Montgomery Bell State Park",
    slug: "montgomery-bell-state-park",
    type: "state_park",
    description: "Set among the rolling hills of Dickson County, Montgomery Bell State Park is Middle Tennessee's premier year-round retreat — a 3,850-acre refuge of hardwood forests, tranquil lakes, and restored 19th-century iron industry heritage. Three spring-fed lakes mirror the surrounding canopy of oak, hickory, and sweetgum, their still surfaces broken only by the rings of rising bluegill and the languid glide of great blue herons. The park's 117-room Lodge at Lake Acorn, extensively renovated and reopened, offers full-service comfort with a restaurant overlooking the water, while 28 miles of trails wind through forests where iron furnace ruins stand as silent monuments to the industrial empire of ironmaster Montgomery Bell, whose operations helped arm the Confederacy and shape the region's economy. The park's peaceful atmosphere belies its historical significance — the Cumberland Presbyterian Church was organized here in 1810, and Bell's iron operations represented one of the most advanced industrial complexes in the antebellum South. Today, golfers enjoy the rolling 18-hole course, paddlers explore the quiet coves of Lake Woodhaven, and families gather at the lakeside swimming beach as fireflies emerge at dusk to light the forest like a galaxy of earthbound stars.",
    editorialSummary: "Middle Tennessee's flagship retreat featuring three serene lakes, a full-service lodge, historic iron furnaces, and championship golf amid rolling hardwood forests.",
    address: "1020 Jackson Hill Rd",
    city: "Burns",
    state: "TN",
    zipCode: "37029",
    lat: 36.1092,
    lng: -87.3308,
    activities: ["hiking", "golf", "fishing", "swimming", "camping", "paddling", "mountain biking", "wildlife viewing", "disc golf"],
    species: ["white-tailed deer", "wild turkey", "great blue heron", "bluegill", "largemouth bass", "red-tailed hawk", "eastern bluebird", "box turtle"],
    gameTypes: ["bluegill", "largemouth bass", "catfish"],
    amenities: ["lodge", "restaurant", "cabins", "camping", "golf course", "swimming beach", "boat rentals", "restrooms", "trails", "picnic shelters", "conference center", "disc golf"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["lodge", "golf", "lakes", "historic", "iron furnaces", "family friendly", "Middle Tennessee"],
    difficulty: "easy",
    regulations: "No entrance fee. Lodge and cabin reservations available online. Golf course open to public — tee time reservations recommended. Fishing license required. Boats limited to electric motors.",
    website: "https://tnstateparks.com/parks/montgomery-bell",
    phone: "(615) 797-9052",
    bookingUrl: "https://reserve.tnstateparks.com",
    permitUrl: null,
    imageUrl: img(TN_LAKE, 2),
    photos: [img(TN_LAKE, 2), img(TN_FOREST, 1), img(TN_TRAIL, 0)],
    rating: 4.6,
    reviews: 4321,
    priceRange: "$$",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: false,
    isVerified: true,
    metadata: {
      acreage: 3850,
      knownFor: "Full-service lakeside lodge, championship golf course, historic iron furnaces, three spring-fed lakes, Cumberland Presbyterian Church birthplace",
      foraging: {
        permitted: "Restricted within park — surrounding Middle TN countryside offers seasonal foraging",
        springEdibles: ["wild garlic and onions in meadows", "dandelion greens", "violets", "chickweed"],
        summerEdibles: ["blackberries along forest edges", "elderberries", "wild black raspberries"],
        fallEdibles: ["persimmons", "black walnuts", "hickory nuts (shagbark and shellbark)", "pawpaws along creek bottoms"],
        mushrooms: ["morels near dead elms and ash (spring)", "chanterelles in oak-hickory forest (summer)", "chicken of the woods on oak stumps"],
        caution: "Foraging restricted within park boundaries. Iron furnace ruins area is historically sensitive — stay on trails."
      }
    },
  },
  {
    name: "Natchez Trace State Park",
    slug: "natchez-trace-state-park",
    type: "state_park",
    description: "Stretching across 48,000 acres of reclaimed Depression-era farmland in the Western Highland Rim, Natchez Trace State Park is one of the largest state parks in Tennessee and a testament to the land's capacity for renewal. What was once overfarmed, eroded terrain — so exhausted that it was among the first properties acquired by the federal Resettlement Administration in the 1930s — has regenerated into a vast tapestry of mature hardwood and pine forest, rolling meadows, and four lakes that together create the finest equestrian park in the state. With 250 miles of horseback riding trails winding through forests and across gentle ridgelines, Natchez Trace draws riders from across the Southeast to its purpose-built wrangler campgrounds. The Pin Oak Lodge perches above one of the park's lakes, its 47 renovated rooms offering comfortable accommodations with panoramic water views. For anglers, the four lakes yield bass, bluegill, and catfish in a setting of almost preternatural quiet. The park's very existence tells the story of conservation at its most hopeful: land that was destroyed by poor agricultural practices, healed by the Civilian Conservation Corps, and returned to a wildness that now shelters deer, turkey, bobcat, and the occasional bald eagle soaring above the pine canopy.",
    editorialSummary: "Tennessee's premier equestrian destination — 48,000 acres of restored forest with 250 miles of riding trails, four lakes, and the historic Pin Oak Lodge.",
    address: "24845 Natchez Trace Rd",
    city: "Wildersville",
    state: "TN",
    zipCode: "38388",
    lat: 35.8397,
    lng: -88.2480,
    activities: ["horseback riding", "hiking", "fishing", "camping", "swimming", "boating", "archery", "wildlife viewing", "mountain biking"],
    species: ["white-tailed deer", "wild turkey", "bobcat", "bald eagle", "red fox", "largemouth bass", "channel catfish", "pine warbler"],
    gameTypes: ["largemouth bass", "bluegill", "catfish", "crappie"],
    amenities: ["lodge", "restaurant", "cabins", "camping", "wrangler camp", "horse stables", "boat rentals", "swimming beach", "archery range", "trails", "restrooms", "picnic areas"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["horseback riding", "equestrian", "lodge", "fishing", "lakes", "CCC history", "West Tennessee"],
    difficulty: "easy",
    regulations: "No entrance fee. Coggins test required for all horses. Wrangler camp reservations available online. Fishing license required. Lodge and cabin reservations recommended well in advance.",
    website: "https://tnstateparks.com/parks/natchez-trace",
    phone: "(731) 968-3742",
    bookingUrl: "https://reserve.tnstateparks.com",
    permitUrl: null,
    imageUrl: img(TN_TRAIL, 1),
    photos: [img(TN_TRAIL, 1), img(TN_LAKE, 0), img(TN_FOREST, 2)],
    rating: 4.5,
    reviews: 3456,
    priceRange: "$",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: false,
    isVerified: true,
    metadata: {
      acreage: 48000,
      knownFor: "Tennessee's finest equestrian park with 250 miles of riding trails, Pin Oak Lodge, and four fishing lakes on beautifully restored Depression-era farmland",
      foraging: {
        permitted: "Some foraging allowed in designated areas — check with rangers",
        springEdibles: ["wild onions in meadows", "dandelion greens", "violets", "poke sallet (young shoots only, must be boiled)"],
        summerEdibles: ["blackberries (abundant on forest edges)", "wild plums", "elderberries", "muscadine grapes"],
        fallEdibles: ["persimmons (prolific)", "black walnuts", "hickory nuts", "pawpaws along streams", "muscadine grapes"],
        mushrooms: ["morels in disturbed areas near dead trees (spring)", "chanterelles in oak-hickory forest", "chicken of the woods", "puffballs in meadows"],
        caution: "48,000 acres means remote areas — carry water, map, and tell someone your plans. Watch for poison ivy along trail edges."
      }
    },
  },
  {
    name: "Rock Island State Park",
    slug: "rock-island-state-park",
    type: "state_park",
    description: "Where the Caney Fork River, Collins River, and Rocky River converge at the foot of the Cumberland Plateau, Rock Island State Park presides over one of Tennessee's most dramatic riverscapes — a collision of whitewater, sandstone gorges, and thundering cascades that has drawn visitors since the early 1800s. The park's centerpiece is the Great Falls, where the Caney Fork plunges over a broad horseshoe dam into a swirling emerald pool surrounded by towering sandstone bluffs. Below the falls, Twin Falls drops in twin ribbons of white through a narrow gorge, accessible by a trail that descends through layers of geological time exposed in the canyon walls. The park's natural swimming areas — broad pools of crystalline water at the base of cascades — are among the most popular wild swimming spots in the state, drawing crowds on summer weekends who come to float in water so clear you can count the pebbles twenty feet down. Above the gorges, the park's uplands offer quiet hiking through mixed hardwood forest and along the rim of the Caney Fork Gorge, with overlooks that frame the river's emerald ribbon hundreds of feet below. The remains of a 19th-century textile mill add historical texture to a landscape that has been harnessing the power of falling water for centuries.",
    editorialSummary: "A dramatic convergence of three rivers with thundering waterfalls, natural swimming holes, and sandstone gorges at the edge of the Cumberland Plateau.",
    address: "82 Beach Rd",
    city: "Rock Island",
    state: "TN",
    zipCode: "38581",
    lat: 35.8069,
    lng: -85.6419,
    activities: ["swimming", "hiking", "fishing", "kayaking", "camping", "photography", "rock climbing", "wildlife viewing"],
    species: ["smallmouth bass", "rainbow trout", "great blue heron", "kingfisher", "sycamore", "eastern hemlock", "maidenhair fern"],
    gameTypes: ["smallmouth bass", "rainbow trout", "rock bass"],
    amenities: ["cabins", "camping", "restrooms", "trails", "swimming area", "boat ramp", "picnic shelters", "playground"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["waterfalls", "swimming holes", "gorge", "kayaking", "confluence", "Great Falls"],
    difficulty: "moderate",
    regulations: "No entrance fee. Swimming at your own risk — no lifeguards. Cabin reservations online. Water levels fluctuate with dam releases — check schedule before swimming or wading.",
    website: "https://tnstateparks.com/parks/rock-island",
    phone: "(931) 686-2471",
    bookingUrl: "https://reserve.tnstateparks.com",
    permitUrl: null,
    imageUrl: img(TN_FALLS, 2),
    photos: [img(TN_FALLS, 2), img(TN_RIVER, 0), img(TN_FALLS, 0)],
    rating: 4.7,
    reviews: 5678,
    priceRange: "$",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: true,
    isVerified: true,
    metadata: {
      acreage: 883,
      knownFor: "Great Falls, Twin Falls, natural swimming holes, convergence of three rivers, sandstone gorge overlooks",
      foraging: {
        permitted: "Restricted within park — surrounding Cumberland Plateau edges offer foraging",
        springEdibles: ["ramps in moist cove forests", "wild ginger along streams", "toothwort", "spring cress in shallow water"],
        summerEdibles: ["blackberries", "serviceberries", "wild black raspberries"],
        fallEdibles: ["pawpaws along river bottoms", "persimmons", "black walnuts"],
        mushrooms: ["morels near sycamore and ash (spring)", "chanterelles in oak forests (summer)", "oyster mushrooms on fallen hardwoods"],
        caution: "River gorge areas are ecologically sensitive. Water levels change rapidly with upstream dam releases."
      }
    },
  },
  {
    name: "Cummins Falls State Park",
    slug: "cummins-falls-state-park",
    type: "state_park",
    description: "Hidden in a narrow gorge of the Blackburn Fork River in Jackson County, Cummins Falls is Tennessee's eighth largest waterfall and one of the state's most rewarding natural adventures. The 75-foot cascade crashes over a broad limestone ledge into a deep, crystalline swimming hole of almost surreal blue-green clarity — a natural infinity pool carved into bedrock over millennia. What makes Cummins Falls extraordinary is the journey to reach it: a rugged, unimproved trail that crosses the river multiple times, scrambles over river boulders, and wades through knee-deep pools before revealing the falls in a sudden, breathtaking reveal around a final bend. This is not a drive-up waterfall — it's an earned experience, and the effort makes the reward all the sweeter. The gorge's microclimate creates a lush, fern-draped environment where maidenhair ferns cling to mist-soaked rock faces and water-polished limestone glows in every shade of cream and gold. Designated a State Park in 2012 after years of grassroots advocacy, Cummins Falls now requires an access permit for the gorge — a necessary measure to protect both the fragile environment and the visitors who come to experience one of Tennessee's most magical natural sanctuaries.",
    editorialSummary: "Tennessee's eighth largest waterfall, a 75-foot cascade into a stunning blue-green swimming hole accessible only by a rugged river-crossing trail.",
    address: "390 Cummins Falls Ln",
    city: "Cookeville",
    state: "TN",
    zipCode: "38501",
    lat: 36.2518,
    lng: -85.5819,
    activities: ["hiking", "swimming", "photography", "wildlife viewing"],
    species: ["maidenhair fern", "walking fern", "hellbender salamander", "smallmouth bass", "belted kingfisher", "water thrush"],
    gameTypes: null,
    amenities: ["restrooms", "trails", "parking", "interpretive signs"],
    seasons: ["spring", "summer", "fall"],
    tags: ["waterfall", "swimming hole", "adventure hike", "river crossing", "gorge", "permit required"],
    difficulty: "hard",
    regulations: "Free access permit required for gorge area — obtain online before visiting. Limited daily permits. River crossings required — water shoes essential. No alcohol. Pets not recommended. Check water levels before going — gorge access closes during high water.",
    website: "https://tnstateparks.com/parks/cummins-falls",
    phone: "(931) 268-7307",
    bookingUrl: null,
    permitUrl: "https://tnstateparks.com/parks/cummins-falls",
    imageUrl: img(TN_FALLS, 0),
    photos: [img(TN_FALLS, 0), img(TN_RIVER, 1), img(TN_FALLS, 1)],
    rating: 4.8,
    reviews: 7234,
    priceRange: "Free",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: true,
    isVerified: true,
    metadata: {
      acreage: 306,
      knownFor: "75-foot waterfall with stunning blue-green swimming hole, adventurous river-crossing trail, permit-required gorge access",
      foraging: {
        permitted: "Restricted within park boundaries",
        springEdibles: ["wild violets", "spring cress along the river"],
        summerEdibles: ["blackberries along gorge rim trails"],
        fallEdibles: ["black walnuts in surrounding areas"],
        mushrooms: ["oyster mushrooms on fallen trees near the gorge"],
        caution: "The gorge is a protected natural area. Harvesting plants or fungi within the park is prohibited."
      }
    },
  },
  {
    name: "Pickwick Landing State Park",
    slug: "pickwick-landing-state-park",
    type: "state_park",
    description: "Where the Tennessee River widens into the vast blue expanse of Pickwick Lake in the far southwestern corner of the state, Pickwick Landing State Park offers Tennessee's finest waterfront resort experience. The park's inn perches on a bluff overlooking 43,100 acres of impounded river — a shimmering inland sea created by Pickwick Dam that stretches to the horizons of Alabama and Mississippi. Championship smallmouth bass fishing draws anglers from across the nation, while the park's full-service marina, sand beach, and lakeside golf course make it a complete vacation destination. The surrounding countryside is steeped in Civil War history — the Battle of Shiloh was fought just miles away — and the Tennessee River itself was a critical strategic corridor throughout the war. Today, the park's 1,400 acres blend modern resort amenities with natural beauty: sunsets over the lake paint the sky in watercolors of peach and violet, while bald eagles patrol the dam tailwaters and osprey dive for shad in the open water. The renovated inn and lakeside cabins provide comfortable bases for exploring the river's quiet coves by kayak, fishing the rocky points for trophy bass, or simply watching the barges glide past on their ancient river highway.",
    editorialSummary: "Tennessee's premier lakeside resort park on the vast Tennessee River, offering championship fishing, marina, golf, and stunning sunset views over Pickwick Lake.",
    address: "Hwy 57",
    city: "Counce",
    state: "TN",
    zipCode: "38326",
    lat: 35.0636,
    lng: -88.2431,
    activities: ["fishing", "boating", "swimming", "golf", "hiking", "camping", "kayaking", "wildlife viewing", "water skiing"],
    species: ["smallmouth bass", "largemouth bass", "striped bass", "bald eagle", "osprey", "great blue heron", "catfish", "crappie"],
    gameTypes: ["smallmouth bass", "largemouth bass", "striped bass", "catfish", "crappie", "sauger"],
    amenities: ["inn", "restaurant", "cabins", "marina", "boat ramp", "boat rentals", "golf course", "swimming beach", "camping", "trails", "conference center", "gift shop"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["lakefront", "fishing", "marina", "resort", "golf", "Tennessee River", "bass fishing"],
    difficulty: "easy",
    regulations: "No entrance fee. Fishing license required. Marina services available seasonally. Inn and cabin reservations online. Golf tee times recommended.",
    website: "https://tnstateparks.com/parks/pickwick-landing",
    phone: "(731) 689-3129",
    bookingUrl: "https://reserve.tnstateparks.com",
    permitUrl: null,
    imageUrl: img(TN_LAKE, 0),
    photos: [img(TN_LAKE, 0), img(TN_LAKE, 1), img(TN_TRAIL, 2)],
    rating: 4.5,
    reviews: 3890,
    priceRange: "$$",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: false,
    isVerified: true,
    metadata: {
      acreage: 1400,
      knownFor: "Championship smallmouth bass fishing on the Tennessee River, full-service marina, lakeside inn and golf course, spectacular sunset views",
      foraging: {
        permitted: "Some foraging in surrounding areas — check local regulations",
        springEdibles: ["wild garlic", "dandelion greens", "chickweed", "wild mustard"],
        summerEdibles: ["blackberries (abundant)", "wild plums", "elderberries", "muscadine grapes"],
        fallEdibles: ["persimmons", "pecans (southern TN has native pecans)", "black walnuts", "hickory nuts"],
        mushrooms: ["morels near dead elms and ash", "chanterelles in hardwood forest", "chicken of the woods on oak"],
        caution: "Lakefront areas are managed by TVA. Check TVA foraging regulations for lands adjacent to the reservoir."
      }
    },
  },
  {
    name: "Cumberland Mountain State Park",
    slug: "cumberland-mountain-state-park",
    type: "state_park",
    description: "Perched atop the Cumberland Plateau in Crossville, Cumberland Mountain State Park is a living monument to the Civilian Conservation Corps and one of the most beautifully crafted parks in the Tennessee system. The park's signature stone and timber structures — built by CCC workers during the 1930s from native Crab Orchard stone — are so expertly constructed that they were placed on the National Register of Historic Places, and they remain among the finest examples of Depression-era rustic architecture in America. Seven original stone cabins offer overnight guests the rare experience of sleeping in historic buildings that embody the craftsmanship of a bygone era, with walls of hand-cut stone two feet thick and massive stone fireplaces that have warmed visitors for nine decades. Byrd Lake, a 50-acre impoundment nestled in a bowl of mixed hardwood forest, serves as the park's centerpiece — its mirror-still surface reflecting the surrounding canopy in autumn's full glory. The Bear Trace at Cumberland Mountain golf course has been ranked among the top ten public courses in North America by Golf Magazine, its rolling fairways carved through native forest with views stretching across the plateau. Mountain biking trails weave through the forest understory, and the park's trail system connects to the larger Cumberland Trail — a still-growing footpath that will eventually stretch 300 miles from Cumberland Gap to Chattanooga.",
    editorialSummary: "A masterpiece of CCC rustic architecture atop the Cumberland Plateau, with historic stone cabins, a top-10 golf course, and connections to the Cumberland Trail.",
    address: "24 Office Dr",
    city: "Crossville",
    state: "TN",
    zipCode: "38555",
    lat: 35.9508,
    lng: -84.9925,
    activities: ["hiking", "golf", "fishing", "camping", "mountain biking", "paddling", "swimming", "wildlife viewing"],
    species: ["white-tailed deer", "wild turkey", "red fox", "pileated woodpecker", "bluegill", "bass", "box turtle", "scarlet tanager"],
    gameTypes: ["bluegill", "largemouth bass", "catfish"],
    amenities: ["cabins", "camping", "restrooms", "trails", "golf course", "restaurant", "swimming pool", "boat rentals", "picnic shelters", "playground", "mountain bike trails"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["CCC architecture", "historic cabins", "golf", "Cumberland Plateau", "Crab Orchard stone", "mountain biking"],
    difficulty: "easy",
    regulations: "No entrance fee. Historic cabins book well in advance. Golf tee times recommended. Mountain bike trails have designated hours. Fishing license required.",
    website: "https://tnstateparks.com/parks/cumberland-mountain",
    phone: "(931) 484-6138",
    bookingUrl: "https://reserve.tnstateparks.com",
    permitUrl: null,
    imageUrl: img(TN_FOREST, 2),
    photos: [img(TN_FOREST, 2), img(TN_LAKE, 0), img(TN_TRAIL, 1)],
    rating: 4.6,
    reviews: 3123,
    priceRange: "$$",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: false,
    isVerified: true,
    metadata: {
      acreage: 1720,
      knownFor: "National Register CCC stone architecture, Bear Trace championship golf (top 10 NA), historic stone cabins, Cumberland Trail access",
      foraging: {
        permitted: "Limited — Cumberland Plateau surrounding the park offers excellent foraging opportunities",
        springEdibles: ["ramps on plateau slopes", "toothwort", "wild ginger", "spring beauty", "creasy greens (wild cress)"],
        summerEdibles: ["blackberries", "wild blueberries on sandstone outcrops", "serviceberries", "wood sorrel"],
        fallEdibles: ["pawpaws along streams", "persimmons", "black walnuts", "hickory nuts", "chinquapin nuts"],
        mushrooms: ["morels near tulip poplar (spring)", "chanterelles in mixed oak forest (summer)", "hen of the woods on old oaks (fall)", "black trumpets in beech groves"],
        caution: "Cumberland Plateau sandstone ledges can be slippery. Some areas contain rare glade plants — do not harvest from any glade habitat."
      }
    },
  },
  {
    name: "Paris Landing State Park",
    slug: "paris-landing-state-park",
    type: "state_park",
    description: "Commanding 841 acres along the western shore of Kentucky Lake — the largest man-made lake east of the Mississippi at 160,000 acres — Paris Landing State Park is West Tennessee's gateway to one of America's greatest freshwater playgrounds. The park's full-service marina, lakeside inn with panoramic dining, and championship golf course create a resort experience rivaling any in the Southeast, while the lake itself stretches to the horizon in every direction, its island-dotted waters offering seemingly infinite coves and channels for exploration. Kentucky Lake's legendary fishing draws tens of thousands of anglers annually for its bass, crappie, and catfish, while the lake's broad waters accommodate everything from sailing and water skiing to houseboat cruises. The park's swim beach, framed by shade trees and overlooking the lake's blue expanse, provides the quintessential summer afternoon, while autumn brings brilliant foliage reflected in the calm waters and the distinctive calls of migrating waterfowl. At sunset, when the western sky ignites over the lake and the water turns to liquid gold, Paris Landing delivers a spectacle that no photograph can fully capture — a daily reminder of why Tennessee's park system consistently ranks among the finest in the nation.",
    editorialSummary: "West Tennessee's lakeside resort on Kentucky Lake — the largest man-made lake east of the Mississippi — with marina, inn, golf, and legendary fishing.",
    address: "16055 Hwy 79 N",
    city: "Buchanan",
    state: "TN",
    zipCode: "38222",
    lat: 36.3728,
    lng: -88.0950,
    activities: ["fishing", "boating", "swimming", "golf", "hiking", "camping", "water skiing", "sailing", "kayaking"],
    species: ["largemouth bass", "smallmouth bass", "crappie", "catfish", "sauger", "bald eagle", "osprey", "great blue heron"],
    gameTypes: ["largemouth bass", "smallmouth bass", "crappie", "catfish", "sauger", "bluegill"],
    amenities: ["inn", "restaurant", "marina", "boat ramp", "boat rentals", "golf course", "swimming beach", "cabins", "camping", "trails", "fish cleaning station", "conference center"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["Kentucky Lake", "fishing", "marina", "resort", "golf", "boating", "West Tennessee"],
    difficulty: "easy",
    regulations: "No entrance fee. Fishing license required (Tennessee or Kentucky depending on location on lake). Marina services seasonal. Inn reservations recommended.",
    website: "https://tnstateparks.com/parks/paris-landing",
    phone: "(731) 641-4465",
    bookingUrl: "https://reserve.tnstateparks.com",
    permitUrl: null,
    imageUrl: img(TN_LAKE, 1),
    photos: [img(TN_LAKE, 1), img(TN_LAKE, 2), img(TN_TRAIL, 0)],
    rating: 4.5,
    reviews: 4123,
    priceRange: "$$",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: false,
    isVerified: true,
    metadata: {
      acreage: 841,
      knownFor: "Gateway to Kentucky Lake (160,000 acres, largest man-made lake east of the Mississippi), full-service marina, lakeside inn with restaurant, championship golf",
      foraging: {
        permitted: "TVA lands surrounding the lake allow limited personal-use foraging",
        springEdibles: ["wild garlic", "dandelion greens", "chickweed", "wild mustard greens"],
        summerEdibles: ["blackberries", "mulberries", "elderberries", "wild plums", "muscadine grapes"],
        fallEdibles: ["persimmons", "pecans", "black walnuts", "hickory nuts", "pawpaws"],
        mushrooms: ["morels near dead elms (spring)", "chanterelles in hardwood bottoms", "chicken of the woods on oak"],
        caution: "TVA manages lands around Kentucky Lake — foraging allowed in reasonable quantities (10% rule) for personal use only, never commercial."
      }
    },
  },
  {
    name: "Frozen Head State Park",
    slug: "frozen-head-state-park",
    type: "state_park",
    description: "Deep in the rugged Cumberland Mountains of Morgan County, Frozen Head State Park protects 24,000 acres of some of the most remote and biologically rich forest in the eastern United States. The park takes its name from Frozen Head Mountain, whose 3,324-foot summit — the highest point on the Cumberland Plateau — collects ice and frost long after the surrounding lowlands have warmed to spring. This is wild, uncompromising mountain country: steep-sided hollows cloak old-growth hemlock and poplar, more than a dozen waterfalls cascade through rhododendron-choked gorges, and the park's 80+ miles of trails traverse terrain so challenging that it hosts the legendary Barkley Marathons — an invitation-only ultramarathon so brutal that in most years no runner finishes at all. But Frozen Head rewards those who venture beyond the trailhead with treasures found nowhere else: spring wildflower displays rivaling the Great Smokies, breeding populations of rare cerulean warblers in the canopy overhead, and a silence so complete that on still mornings you can hear the wingbeats of ravens passing above the ridge. The park's rehabilitation from decades of coal mining damage makes its current wildness all the more remarkable — proof that given time and protection, even the most scarred landscapes can return to glory.",
    editorialSummary: "24,000 acres of wild Cumberland Mountain wilderness, home to the infamous Barkley Marathons, stunning spring wildflowers, and the highest point on the Cumberland Plateau.",
    address: "964 Flat Fork Rd",
    city: "Wartburg",
    state: "TN",
    zipCode: "37887",
    lat: 36.1317,
    lng: -84.4257,
    activities: ["hiking", "backpacking", "wildlife viewing", "photography", "camping", "wildflower viewing", "trail running"],
    species: ["cerulean warbler", "black bear", "timber rattlesnake", "hellbender salamander", "eastern hemlock", "tulip poplar", "trillium", "lady slipper orchid"],
    gameTypes: null,
    amenities: ["camping", "restrooms", "trails", "picnic areas", "ranger station"],
    seasons: ["spring", "summer", "fall"],
    tags: ["Barkley Marathons", "wilderness", "wildflowers", "Cumberland Mountains", "remote", "ultramarathon", "old-growth"],
    difficulty: "hard",
    regulations: "No entrance fee. Backcountry camping by permit only — register at trailhead. Weather changes rapidly at elevation. Some trails closed seasonally for wildlife management. No motorized vehicles on trails.",
    website: "https://tnstateparks.com/parks/frozen-head",
    phone: "(423) 346-3318",
    bookingUrl: null,
    permitUrl: "https://tnstateparks.com/parks/frozen-head",
    imageUrl: img(TN_MTN, 1),
    photos: [img(TN_MTN, 1), img(TN_FOREST, 0), img(TN_FALLS, 2)],
    rating: 4.8,
    reviews: 2890,
    priceRange: "Free",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: true,
    isVerified: true,
    metadata: {
      acreage: 24000,
      knownFor: "Barkley Marathons ultramarathon, highest point on Cumberland Plateau, spectacular spring wildflowers, remote wilderness hiking, coal mining rehabilitation success story",
      foraging: {
        permitted: "Limited foraging allowed in some areas — check with rangers",
        springEdibles: ["ramps (prolific in rich cove forests)", "wild ginger", "toothwort", "spring beauty", "trout lily leaves"],
        summerEdibles: ["blackberries on old mining roads", "wild blueberries at elevation", "serviceberries", "wood sorrel"],
        fallEdibles: ["pawpaws in rich hollows", "persimmons at lower elevations", "black walnuts", "hickory nuts"],
        mushrooms: ["morels near tulip poplar and dead ash (spring — Frozen Head is legendary morel territory)", "chanterelles (summer)", "hen of the woods (fall)", "black trumpets in beech forests"],
        caution: "Remote terrain — carry map, compass, and supplies. Timber rattlesnakes present on rocky slopes. Some old mining areas may have unstable ground."
      }
    },
  },
  {
    name: "Meeman-Shelby Forest State Park",
    slug: "meeman-shelby-forest-state-park",
    type: "state_park",
    description: "Rising from the Mississippi River floodplain just 13 miles north of downtown Memphis, Meeman-Shelby Forest State Park preserves 12,539 acres of bottomland hardwood forest and cypress swamp — one of the largest intact tracts of old-growth floodplain forest remaining in the lower Mississippi Valley. This is the forest primeval: towering bald cypress trees draped in resurrection fern stand knee-deep in black water, their buttressed trunks reaching skyward through a canopy so dense that the forest floor lies in perpetual twilight. Poplar Tree Lake, an oxbow lake left behind by the river's ancient wanderings, provides still-water paddling through corridors of cypress and tupelo, while the park's 20 miles of trails wind through a living encyclopedia of bottomland ecology — sweetgum, overcup oak, swamp chestnut oak, and persimmon rising from soil enriched by millennia of Mississippi floods. For birders, Meeman-Shelby is a revelation: prothonotary warblers flash golden among the cypress knees, barred owls trade eerie calls across the swamp, and during migration seasons the forest canopy comes alive with warblers, tanagers, and vireos refueling on their journey along the Mississippi Flyway. The park's proximity to Memphis makes it an urban wilderness of extraordinary importance — a remnant of the vast forests that once lined the entire lower Mississippi.",
    editorialSummary: "12,500 acres of primeval Mississippi bottomland forest and cypress swamp just north of Memphis — a critical remnant of the great river's vanished wilderness.",
    address: "910 Riddick Rd",
    city: "Millington",
    state: "TN",
    zipCode: "38053",
    lat: 35.3489,
    lng: -90.0325,
    activities: ["hiking", "kayaking", "canoeing", "fishing", "camping", "birding", "horseback riding", "mountain biking", "wildlife viewing"],
    species: ["bald cypress", "prothonotary warbler", "barred owl", "white-tailed deer", "wild turkey", "river otter", "swamp rabbit", "pileated woodpecker", "red-shouldered hawk"],
    gameTypes: ["largemouth bass", "bluegill", "catfish", "crappie"],
    amenities: ["cabins", "camping", "restrooms", "trails", "boat ramp", "boat rentals", "swimming pool", "nature center", "disc golf", "picnic shelters"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["bottomland forest", "cypress swamp", "Mississippi River", "birding", "Memphis", "old-growth", "kayaking"],
    difficulty: "easy",
    regulations: "No entrance fee. Some trails flood seasonally — check conditions before hiking bottomland trails. Fishing license required. Horseback riding on designated trails only.",
    website: "https://tnstateparks.com/parks/meeman-shelby",
    phone: "(901) 876-5756",
    bookingUrl: "https://reserve.tnstateparks.com",
    permitUrl: null,
    imageUrl: img(TN_FOREST, 1),
    photos: [img(TN_FOREST, 1), img(TN_LAKE, 0), img(TN_FOREST, 2)],
    rating: 4.6,
    reviews: 3456,
    priceRange: "$",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: false,
    isVerified: true,
    metadata: {
      acreage: 12539,
      knownFor: "One of the largest intact bottomland hardwood forests in the lower Mississippi Valley, cypress swamp paddling, Mississippi Flyway birding, urban wilderness near Memphis",
      foraging: {
        permitted: "Some foraging allowed — check with rangers for current regulations",
        springEdibles: ["wild garlic in floodplain meadows", "cattail shoots along lake edges", "chickweed", "dandelion"],
        summerEdibles: ["blackberries", "mulberries (very abundant in bottomland)", "elderberries", "wild plums", "muscadine grapes"],
        fallEdibles: ["persimmons (thick stands throughout the park)", "pecans", "black walnuts", "hickory nuts", "pawpaws along creek bottoms"],
        mushrooms: ["oyster mushrooms on fallen hardwoods (year-round)", "morels near dead elms and cottonwoods (spring)", "chicken of the woods on oak", "lion's mane on beech (rare but present)"],
        caution: "Bottomland areas flood regularly — check conditions. Poison ivy extremely abundant in floodplain forest. Watch for water moccasins near cypress swamps."
      }
    },
  },
  {
    name: "Standing Stone State Park",
    slug: "standing-stone-state-park",
    type: "state_park",
    description: "Named for a legendary 12-foot stone monolith that once served as a boundary marker between Cherokee and Shawnee hunting grounds on the Cumberland Plateau, Standing Stone State Park occupies 855 acres of gentle upland forest surrounding the 69-acre Standing Stone Lake. This is the quiet Tennessee — no thundering waterfalls or dramatic gorges, but rather a place of small, accumulated beauties: sunlight filtering through a canopy of sugar maple and white oak, the liquid song of a wood thrush echoing through the hollow, the soft plop of a painted turtle sliding from a sun-warmed log. The park's cabins — a mix of vintage CCC-era rustic and modern deluxe — overlook the lake through screens of dogwood and redbud that ignite with blossoms each April. A seasonal swimming pool and lakeside boat dock provide summer recreation, while miles of trails wind through forests rich in wildflowers, ferns, and the distinctive layered sandstone formations that characterize the plateau's geology. Standing Stone represents what a state park can be at its most essential: a place of refuge and renewal, where the rhythms of the natural world reassert themselves over the noise of modern life.",
    editorialSummary: "A peaceful Cumberland Plateau retreat named for an ancient Cherokee-Shawnee boundary stone, offering quiet lakeside cabins and gentle forest trails.",
    address: "1674 Standing Stone Park Hwy",
    city: "Hilham",
    state: "TN",
    zipCode: "38568",
    lat: 36.4709,
    lng: -85.4139,
    activities: ["hiking", "fishing", "swimming", "camping", "boating", "wildlife viewing", "photography"],
    species: ["white-tailed deer", "wild turkey", "wood thrush", "painted turtle", "sugar maple", "white oak", "dogwood", "redbud"],
    gameTypes: ["largemouth bass", "bluegill", "catfish"],
    amenities: ["cabins", "camping", "restrooms", "trails", "swimming pool", "boat dock", "boat rentals", "picnic shelters", "playground"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["peaceful", "lakeside", "cabins", "Cumberland Plateau", "Cherokee history", "family friendly"],
    difficulty: "easy",
    regulations: "No entrance fee. Cabin reservations online. Electric motors only on lake. Swimming pool seasonal (Memorial Day to Labor Day). Fishing license required.",
    website: "https://tnstateparks.com/parks/standing-stone",
    phone: "(931) 823-6347",
    bookingUrl: "https://reserve.tnstateparks.com",
    permitUrl: null,
    imageUrl: img(TN_LAKE, 2),
    photos: [img(TN_LAKE, 2), img(TN_FOREST, 0), img(TN_TRAIL, 2)],
    rating: 4.5,
    reviews: 1890,
    priceRange: "$",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: false,
    isVerified: true,
    metadata: {
      acreage: 855,
      knownFor: "Named for ancient Cherokee-Shawnee boundary stone, peaceful lakeside setting, CCC-era cabins, Cumberland Plateau wildflowers, gentle family hiking",
      foraging: {
        permitted: "Limited — surrounding Cumberland Plateau areas offer foraging opportunities",
        springEdibles: ["ramps in moist cove forests", "wild ginger", "creasy greens (wild cress)", "toothwort", "violets"],
        summerEdibles: ["blackberries (abundant on plateau)", "wild blueberries on sandstone outcrops", "elderberries"],
        fallEdibles: ["persimmons", "black walnuts", "hickory nuts (shagbark)", "pawpaws along streams"],
        mushrooms: ["morels (spring — good territory on the upper plateau)", "chanterelles in oak forests (summer)", "hen of the woods (fall)", "puffballs in meadows"],
        caution: "Standing Stone area is prime copperhead habitat — watch where you step in rocky areas."
      }
    },
  },
  {
    name: "Edgar Evins State Park",
    slug: "edgar-evins-state-park",
    type: "state_park",
    description: "Perched on a wooded peninsula jutting into the emerald waters of Center Hill Lake, Edgar Evins State Park offers a unique combination of highland forest hiking and deep-water lake recreation in the scenic Upper Cumberland region. The park's 6,000 acres of forested ridgeline and lakeshore embrace a landscape shaped by the ancient forces that carved the Highland Rim — steep, wooded ravines descending to quiet lake coves where morning fog hangs in veils of silver above water so clear you can see the rocky bottom thirty feet below. Center Hill Lake itself, a 18,220-acre reservoir of the Caney Fork River, has earned a reputation as one of Tennessee's cleanest and most beautiful lakes, its cool, deep waters supporting a thriving population of walleye, smallmouth bass, and striped bass. The park's marina provides boat rentals and slip access, while the Millennium Trail winds along the ridge through mature oak-hickory forest with periodic overlooks offering sweeping views across the lake to the distant plateau. Rustic cabins tucked into the forest canopy provide accommodation that feels genuinely remote despite the park's easy access from Interstate 40. At the junction of the Cumberland Plateau and the Highland Rim, Edgar Evins occupies a transitional landscape where upland and lowland ecosystems meet — creating exceptional biological diversity in a setting of uncommon beauty.",
    editorialSummary: "A forested peninsula on crystal-clear Center Hill Lake, offering deep-water fishing, marina access, and Highland Rim forest trails in the Upper Cumberland.",
    address: "1630 Edgar Evins State Park Rd",
    city: "Silver Point",
    state: "TN",
    zipCode: "38582",
    lat: 36.0772,
    lng: -85.7397,
    activities: ["fishing", "boating", "hiking", "camping", "swimming", "kayaking", "wildlife viewing"],
    species: ["walleye", "smallmouth bass", "striped bass", "largemouth bass", "white-tailed deer", "wild turkey", "pileated woodpecker", "osprey"],
    gameTypes: ["walleye", "smallmouth bass", "striped bass", "largemouth bass", "crappie"],
    amenities: ["cabins", "camping", "marina", "boat ramp", "boat rentals", "restrooms", "trails", "picnic shelters"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["Center Hill Lake", "fishing", "marina", "clear water", "walleye", "Upper Cumberland"],
    difficulty: "moderate",
    regulations: "No entrance fee. Fishing license required. Marina services seasonal. Cabin reservations online. Some trails steep with exposed roots — proper footwear recommended.",
    website: "https://tnstateparks.com/parks/edgar-evins",
    phone: "(931) 858-2114",
    bookingUrl: "https://reserve.tnstateparks.com",
    permitUrl: null,
    imageUrl: img(TN_LAKE, 0),
    photos: [img(TN_LAKE, 0), img(TN_FOREST, 1), img(TN_TRAIL, 0)],
    rating: 4.5,
    reviews: 2345,
    priceRange: "$",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: false,
    isVerified: true,
    metadata: {
      acreage: 6000,
      knownFor: "Crystal-clear Center Hill Lake, walleye fishing, forested peninsula setting, Highland Rim-Cumberland Plateau transition zone",
      foraging: {
        permitted: "Limited within park — surrounding Highland Rim and plateau areas excellent for foraging",
        springEdibles: ["ramps in cove forests", "wild ginger", "toothwort", "chickweed", "spring beauty"],
        summerEdibles: ["blackberries along trail edges", "elderberries near lake margins", "serviceberries"],
        fallEdibles: ["pawpaws in ravine bottoms", "persimmons", "black walnuts", "hickory nuts"],
        mushrooms: ["morels near tulip poplars (spring)", "chanterelles in oak-hickory forest (summer)", "oyster mushrooms on fallen hardwoods"],
        caution: "Steep ravines near lake — stay on trails. Center Hill Lake has cold, deep water — use caution swimming."
      }
    },
  },
  {
    name: "Savage Gulf State Natural Area",
    slug: "savage-gulf-state-natural-area",
    type: "state_park",
    description: "Within the greater South Cumberland State Park system, Savage Gulf State Natural Area protects one of the most awe-inspiring geological features in the eastern United States — a system of deep sandstone gorges carved over millions of years by the Savage Creek, Collins River, and their tributaries into the Cumberland Plateau. The Stone Door, a massive crack in the plateau rim that served as a passageway for Native Americans descending into the gulf, remains the park's most famous feature — a narrow slot canyon that opens onto a vertiginous overlook 900 feet above the gulf floor. From this natural portal, the view stretches across a sea of unbroken forest filling the gorge below, a canopy so vast and primeval it recalls what much of the eastern United States looked like before European settlement. The gulf system encompasses three major gorges and over 55 miles of trails ranging from gentle rim walks to strenuous descents to the creek-laced floor, where virgin hemlock and tulip poplar tower above streams flowing over beds of ancient sandstone. Greeter Falls, a stunning double waterfall accessible by a shorter trail, provides a more approachable introduction to the gulf's grandeur. Savage Gulf is a landscape that demands time, preparation, and respect — and rewards those who give it with experiences that etch themselves permanently into memory.",
    editorialSummary: "One of the deepest gorge systems east of the Mississippi, featuring the iconic Stone Door passage, 900-foot cliffs, and 55 miles of wilderness trails.",
    address: "3157 SR 399",
    city: "Palmer",
    state: "TN",
    zipCode: "37365",
    lat: 35.3600,
    lng: -85.6000,
    activities: ["hiking", "backpacking", "rock climbing", "photography", "wildlife viewing", "camping"],
    species: ["eastern hemlock", "tulip poplar", "Cumberland rosinweed", "timber rattlesnake", "black bear", "peregrine falcon", "green salamander", "cerulean warbler"],
    gameTypes: null,
    amenities: ["backcountry camping", "restrooms", "trails", "ranger station", "interpretive signs", "parking"],
    seasons: ["spring", "summer", "fall"],
    tags: ["Stone Door", "gorge", "wilderness", "backpacking", "Greeter Falls", "cliffs", "old-growth"],
    difficulty: "hard",
    regulations: "Backcountry permits required for overnight camping. No fires except at designated backcountry sites. Stay on marked trails near cliff edges. Register at trailhead kiosk. Water from streams must be treated.",
    website: "https://tnstateparks.com/parks/savage-gulf",
    phone: "(931) 779-3532",
    bookingUrl: null,
    permitUrl: "https://tnstateparks.com/parks/savage-gulf",
    imageUrl: img(TN_MTN, 2),
    photos: [img(TN_MTN, 2), img(TN_FALLS, 1), img(TN_FOREST, 0)],
    rating: 4.9,
    reviews: 4567,
    priceRange: "Free",
    providerType: "public",
    jurisdiction: "state",
    source: "manual",
    sourceId: null,
    isFeatured: true,
    isVerified: true,
    metadata: {
      acreage: 15590,
      knownFor: "Stone Door overlook (iconic plateau passage), 900-foot gorge walls, Greeter Falls, 55 miles of trails, old-growth forest, one of deepest gorges east of the Mississippi",
      foraging: {
        permitted: "Restricted — this is a State Natural Area with strict no-harvest protections",
        notableFlora: ["old-growth hemlock and tulip poplar in gorge bottoms", "rare Cumberland Plateau endemics on cliff faces", "diverse fern communities including walking fern and maidenhair"],
        springEdibles: ["In surrounding areas: ramps, toothwort, wild ginger"],
        mushrooms: ["Observation only within SNA — surrounding plateau forests offer morels, chanterelles, and hen of the woods"],
        caution: "All plants and fungi protected within State Natural Area boundaries. Gorge environment is ecologically fragile. Cliff edges are unguarded — extreme caution required."
      }
    },
  },

  // ===== TENNESSEE NATIONAL PARK SITES =====
  {
    name: "Big South Fork National River and Recreation Area",
    slug: "big-south-fork-nrra",
    type: "national_park",
    description: "Straddling the Tennessee-Kentucky border in the northern Cumberland Plateau, Big South Fork National River and Recreation Area protects 125,000 acres of the most spectacular river gorge system in the southeastern United States. The Big South Fork of the Cumberland River and its tributaries have carved a labyrinth of sandstone gorges, natural arches, rock shelters, and towering bluffs through 300 million years of plateau geology — creating a landscape so rugged and inaccessible that it remained one of the last true wilderness areas east of the Mississippi well into the 20th century. Over 150 miles of trails traverse terrain ranging from gentle riverside paths to challenging gorge rim routes, while the river itself offers Class III-IV whitewater paddling through corridors of sheer sandstone that glow amber and rose in afternoon light. Natural arches — including the iconic Twin Arches, the largest natural bridge system east of the Rockies — pierce the plateau rim like portals to another world. The Bandy Creek area provides developed camping and visitor facilities, while the Blue Heron Mining Community interprets the harsh lives of coal miners who worked these remote hollows into the 1960s. For horseback riders, over 180 miles of equestrian trails make Big South Fork one of the premier riding destinations in the eastern United States.",
    editorialSummary: "125,000 acres of spectacular Cumberland Plateau gorges, natural arches, whitewater rivers, and the Twin Arches — the largest natural bridge system in the eastern US.",
    address: "4564 Leatherwood Rd",
    city: "Oneida",
    state: "TN",
    zipCode: "37841",
    lat: 36.4871,
    lng: -84.6987,
    activities: ["hiking", "horseback riding", "kayaking", "whitewater rafting", "camping", "rock climbing", "fishing", "mountain biking", "swimming", "photography"],
    species: ["black bear", "white-tailed deer", "wild turkey", "cerulean warbler", "Indiana bat", "muskellunge", "smallmouth bass", "Virginia big-eared bat"],
    gameTypes: ["smallmouth bass", "rock bass", "muskellunge"],
    amenities: ["visitor center", "camping", "backcountry camping", "restrooms", "trails", "horse camps", "picnic areas", "interpretive center"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["Twin Arches", "natural arches", "whitewater", "gorges", "horseback riding", "Cumberland Plateau", "wilderness"],
    difficulty: "moderate",
    regulations: "No entrance fee. Backcountry camping by permit. Whitewater difficulty varies with water level — check conditions. Hunting allowed in designated areas during season. Coggins test required for horses.",
    website: "https://www.nps.gov/biso/index.htm",
    phone: "(423) 286-7275",
    bookingUrl: "https://www.recreation.gov",
    permitUrl: "https://www.nps.gov/biso/planyourvisit/permits.htm",
    imageUrl: img(TN_MTN, 0),
    photos: [img(TN_MTN, 0), img(TN_RIVER, 0), img(TN_FOREST, 1)],
    rating: 4.8,
    reviews: 5678,
    priceRange: "Free",
    providerType: "public",
    jurisdiction: "federal",
    source: "manual",
    sourceId: null,
    isFeatured: true,
    isVerified: true,
    metadata: {
      acreage: 125000,
      knownFor: "Twin Arches (largest natural bridge system east of Rockies), Class III-IV whitewater, 150+ miles of trails, premier horseback riding, Blue Heron ghost mining town",
      foraging: {
        permitted: "Personal-use foraging of fruits, nuts, and berries allowed — no digging or uprooting plants. Mushroom gathering allowed for personal consumption.",
        springEdibles: ["ramps (prolific in rich cove forests)", "wild ginger", "toothwort", "spring beauty", "creasy greens (wild cress)", "wild leeks"],
        summerEdibles: ["blackberries (abundant on old roads and clearings)", "wild blueberries on plateau rim", "serviceberries", "elderberries"],
        fallEdibles: ["pawpaws in gorge bottoms (excellent habitat)", "persimmons", "black walnuts", "hickory nuts", "chinquapin nuts"],
        mushrooms: ["morels near dead ash and tulip poplar (spring — Big South Fork is premier morel territory)", "chanterelles in oak forests (summer)", "chicken of the woods on dead oaks", "hen of the woods (fall)", "black trumpets in beech groves"],
        caution: "NPS regulations: collect only for personal use, never commercial. No digging or uprooting. Ginseng harvest prohibited. Remote terrain — carry map and supplies."
      }
    },
  },
  {
    name: "Obed Wild and Scenic River",
    slug: "obed-wild-scenic-river",
    type: "national_park",
    description: "Designated as one of only 226 Wild and Scenic Rivers in the National Park system, the Obed River and its tributary Clear Creek have carved deep, narrow gorges through the Cumberland Plateau east of Crossville — creating a corridor of extraordinary natural beauty that harbors some of the finest rock climbing and whitewater paddling in the Southeast. The river's gorges are intimate and dramatic: sheer sandstone walls rising 80 to 500 feet above boulder-strewn rapids, their faces adorned with curtains of wild hydrangea, hemlock, and rhododendron that soften the raw geometry of the stone. World-class rock climbing routes line the gorge walls, drawing climbers from across the nation to crack systems and overhanging faces of bullet-hard Rockcastle conglomerate. When water levels are right, the Obed and Clear Creek offer technical Class III-IV whitewater through continuous boulder gardens — a wild, committing run through gorges so deep and narrow that once you launch, the only way out is downstream. Below the rapids, quiet pools of emerald water invite swimming, while the surrounding plateau forests support populations of rare mussels, hellbender salamanders, and a diversity of aquatic life that earned the rivers their Wild and Scenic designation.",
    editorialSummary: "A National Wild and Scenic River cutting deep gorges through the Cumberland Plateau, offering world-class rock climbing and technical whitewater in an intimate canyon setting.",
    address: "208 N Maiden St",
    city: "Wartburg",
    state: "TN",
    zipCode: "37887",
    lat: 36.1050,
    lng: -84.5875,
    activities: ["rock climbing", "kayaking", "whitewater paddling", "hiking", "swimming", "fishing", "photography", "wildlife viewing"],
    species: ["hellbender salamander", "smallmouth bass", "rock bass", "cerulean warbler", "bald eagle", "peregrine falcon", "eastern hemlock", "wild hydrangea"],
    gameTypes: ["smallmouth bass", "rock bass"],
    amenities: ["visitor center", "restrooms", "trails", "parking", "interpretive exhibits", "picnic areas"],
    seasons: ["spring", "summer", "fall"],
    tags: ["wild and scenic river", "rock climbing", "whitewater", "gorge", "Cumberland Plateau", "bouldering"],
    difficulty: "hard",
    regulations: "No entrance fee. Rock climbing does not require permit but registration recommended. Whitewater paddling for experienced only — no outfitter services within park. Water levels change rapidly. Swimming at your own risk.",
    website: "https://www.nps.gov/obed/index.htm",
    phone: "(423) 346-6294",
    bookingUrl: null,
    permitUrl: null,
    imageUrl: img(TN_RIVER, 0),
    photos: [img(TN_RIVER, 0), img(TN_MTN, 1), img(TN_RIVER, 2)],
    rating: 4.7,
    reviews: 2345,
    priceRange: "Free",
    providerType: "public",
    jurisdiction: "federal",
    source: "manual",
    sourceId: null,
    isFeatured: false,
    isVerified: true,
    metadata: {
      acreage: 5057,
      knownFor: "National Wild and Scenic River, world-class rock climbing on Rockcastle conglomerate, technical Class III-IV whitewater, deep narrow gorges, hellbender salamander habitat",
      foraging: {
        permitted: "Limited personal-use foraging of fruits, nuts, and berries allowed on NPS land",
        springEdibles: ["ramps in cove forests", "wild ginger", "spring cress along streams"],
        summerEdibles: ["blackberries along rim trails", "serviceberries", "wild blueberries on plateau"],
        fallEdibles: ["pawpaws in gorge bottoms", "black walnuts", "hickory nuts"],
        mushrooms: ["morels near dead hardwoods (spring)", "chanterelles in oak forests", "oyster mushrooms on fallen trees"],
        caution: "Gorge walls are steep and dangerous — stay on trails. River access points are limited. No ginseng harvest on NPS land."
      }
    },
  },
  {
    name: "Stones River National Battlefield",
    slug: "stones-river-national-battlefield",
    type: "national_park",
    description: "On the frozen fields outside Murfreesboro in the closing days of 1862, the Union Army of the Cumberland and the Confederate Army of Tennessee clashed in one of the bloodiest battles of the Civil War — a three-day struggle that produced nearly 24,000 casualties and helped secure Union control of Middle Tennessee. Today, Stones River National Battlefield preserves 570 acres of this hallowed ground, where limestone cedar glades and open meadows are dotted with cannon positions, monuments, and the somber ranks of white headstones in Stones River National Cemetery — the oldest national cemetery established during the Civil War. The park's auto tour and walking trails guide visitors through the battle's key phases: the devastating Confederate dawn attack through the Round Forest, the desperate Union stand along the Nashville Pike, and the final Union assault across McFadden's Ford that decided the battle's outcome. The landscape itself tells the story — the cedar glades that provided concealment, the limestone outcrops that served as natural breastworks, and the river crossing where the battle reached its climax. Beyond its military significance, the battlefield preserves some of the finest remaining examples of Middle Tennessee's rare cedar glade ecosystem, supporting several plant species found nowhere else on Earth.",
    editorialSummary: "Hallowed Civil War battlefield preserving the site of one of the war's bloodiest engagements, featuring the oldest national military cemetery and rare cedar glade ecosystems.",
    address: "3501 Old Nashville Hwy",
    city: "Murfreesboro",
    state: "TN",
    zipCode: "37129",
    lat: 35.8776,
    lng: -86.4340,
    activities: ["hiking", "history", "photography", "birding", "cycling", "ranger programs"],
    species: ["Tennessee coneflower", "limestone fame flower", "cedar glade St. John's wort", "eastern red cedar", "eastern bluebird", "red-tailed hawk"],
    gameTypes: null,
    amenities: ["visitor center", "museum", "restrooms", "trails", "auto tour", "bookstore", "picnic areas", "ranger programs"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["Civil War", "battlefield", "cemetery", "history", "cedar glades", "Murfreesboro", "monuments"],
    difficulty: "easy",
    regulations: "Free admission. Open daily dawn to dusk, visitor center 9-5. No metal detecting. Stay on marked trails in glade areas — plants are federally protected. Bicycles on paved trails only.",
    website: "https://www.nps.gov/stri/index.htm",
    phone: "(615) 893-9501",
    bookingUrl: null,
    permitUrl: null,
    imageUrl: img(TN_TRAIL, 2),
    photos: [img(TN_TRAIL, 2), img(TN_FOREST, 0), img(TN_PARKS, 1)],
    rating: 4.6,
    reviews: 3567,
    priceRange: "Free",
    providerType: "public",
    jurisdiction: "federal",
    source: "manual",
    sourceId: null,
    isFeatured: false,
    isVerified: true,
    metadata: {
      acreage: 570,
      knownFor: "One of the bloodiest Civil War battles (23,515 casualties), oldest national military cemetery, rare cedar glade ecosystem with federally protected endemic plants",
      foraging: {
        permitted: "Prohibited — national battlefield and protected ecosystem",
        notableFlora: ["Tennessee coneflower (federally protected)", "limestone fame flower", "cedar glade St. John's wort", "Nashville breadroot"],
        caution: "All plants and natural materials are fully protected on NPS land. Cedar glade plants include several federally endangered species — never disturb."
      }
    },
  },
  {
    name: "Andrew Johnson National Historic Site",
    slug: "andrew-johnson-national-historic-site",
    type: "national_park",
    description: "In the mountain town of Greeneville, the story of America's seventeenth president — and one of its most controversial — unfolds across a cluster of preserved buildings that trace Andrew Johnson's remarkable rise from impoverished tailor's apprentice to the presidency of a fractured nation. The site preserves Johnson's modest tailor shop, where the self-educated craftsman taught himself to read with the help of his wife Eliza; his family homestead, furnished with original artifacts from the turbulent Reconstruction era; and the hillside cemetery where Johnson lies beneath a monument topped by an eagle clutching the Constitution. Johnson's is a uniquely American story of radical social mobility, political courage, and deep controversy — the only president ever impeached until the modern era, a Southern Unionist who defied the Confederacy and then clashed with his own party over the direction of Reconstruction. The surrounding town of Greeneville, one of the oldest settlements in Tennessee, provides a charming East Tennessee mountain backdrop, with views of the Blue Ridge foothills and a historic downtown that still carries echoes of the antebellum era.",
    editorialSummary: "The preserved homes, tailor shop, and burial site of America's seventeenth president in the historic East Tennessee mountain town of Greeneville.",
    address: "121 Monument Ave",
    city: "Greeneville",
    state: "TN",
    zipCode: "37743",
    lat: 36.1634,
    lng: -82.8310,
    activities: ["history", "museum tours", "photography", "ranger programs"],
    species: [],
    gameTypes: null,
    amenities: ["visitor center", "museum", "restrooms", "gift shop", "ranger programs", "parking"],
    seasons: ["spring", "summer", "fall", "winter"],
    tags: ["presidential history", "Civil War", "Reconstruction", "East Tennessee", "museum", "historic site"],
    difficulty: "easy",
    regulations: "Free admission. Guided tours available — check schedule. Museum and homestead hours vary seasonally. No photography inside historic buildings.",
    website: "https://www.nps.gov/anjo/index.htm",
    phone: "(423) 638-3551",
    bookingUrl: null,
    permitUrl: null,
    imageUrl: img(TN_PARKS, 0),
    photos: [img(TN_PARKS, 0), img(TN_PARKS, 1), img(TN_PARKS, 2)],
    rating: 4.4,
    reviews: 1234,
    priceRange: "Free",
    providerType: "public",
    jurisdiction: "federal",
    source: "manual",
    sourceId: null,
    isFeatured: false,
    isVerified: true,
    metadata: {
      acreage: 17,
      knownFor: "Home and tailor shop of 17th President Andrew Johnson, Reconstruction-era history, only Southern senator to remain loyal to the Union",
      foraging: {
        permitted: "Not applicable — urban historic site",
        nearbyForaging: "East Tennessee's Appalachian foothills surrounding Greeneville offer excellent foraging: ramps, morels, pawpaws, wild blueberries, and chanterelles in nearby Cherokee National Forest."
      }
    },
  },
];

export async function seedTennesseeCatalog() {
  console.log("Checking for Tennessee catalog additions...");

  let added = 0;
  for (const loc of tennesseeLocations) {
    const existing = await db.select({ id: catalogLocations.id })
      .from(catalogLocations)
      .where(eq(catalogLocations.slug, loc.slug))
      .limit(1);

    if (existing.length > 0) {
      continue;
    }

    await db.insert(catalogLocations).values(loc as any);
    added++;
    console.log(`  Added: ${loc.name}`);
  }

  if (added === 0) {
    console.log("All Tennessee locations already exist, skipping.");
  } else {
    console.log(`Successfully added ${added} Tennessee locations to catalog.`);
  }
}

export default seedTennesseeCatalog;
